/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DiagnosticRequest,
    DiagnosticRequestFromJSON,
    DiagnosticRequestToJSON,
} from '../models/DiagnosticRequest';
import {
    type DiagnosticResponse,
    DiagnosticResponseFromJSON,
    DiagnosticResponseToJSON,
} from '../models/DiagnosticResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type RiskAuditRequest,
    RiskAuditRequestFromJSON,
    RiskAuditRequestToJSON,
} from '../models/RiskAuditRequest';
import {
    type RiskAuditV2Response,
    RiskAuditV2ResponseFromJSON,
    RiskAuditV2ResponseToJSON,
} from '../models/RiskAuditV2Response';

export interface CreateDiagnosticV1AnalyzeDiagnosticPostRequest {
    /**
     * 
     */
    diagnosticRequest: DiagnosticRequest;
}

export interface CreateRiskAuditV1AnalyzeRiskAuditPostRequest {
    /**
     * 
     */
    riskAuditRequest: RiskAuditRequest;
}

/**
 * 
 */
export class AnalysisApi extends runtime.BaseAPI {

    /**
     * Creates request options for createDiagnosticV1AnalyzeDiagnosticPost without sending the request
     */
    async createDiagnosticV1AnalyzeDiagnosticPostRequestOpts(requestParameters: CreateDiagnosticV1AnalyzeDiagnosticPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['diagnosticRequest'] == null) {
            throw new runtime.RequiredError(
                'diagnosticRequest',
                'Required parameter "diagnosticRequest" was null or undefined when calling createDiagnosticV1AnalyzeDiagnosticPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/analyze/diagnostic`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DiagnosticRequestToJSON(requestParameters['diagnosticRequest']),
        };
    }

    /**
     * Analyze a call transcript — 5 parallel analyses
     */
    async createDiagnosticV1AnalyzeDiagnosticPostRaw(requestParameters: CreateDiagnosticV1AnalyzeDiagnosticPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiagnosticResponse>> {
        const requestOptions = await this.createDiagnosticV1AnalyzeDiagnosticPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiagnosticResponseFromJSON(jsonValue));
    }

    /**
     * Analyze a call transcript — 5 parallel analyses
     */
    async createDiagnosticV1AnalyzeDiagnosticPost(requestParameters: CreateDiagnosticV1AnalyzeDiagnosticPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiagnosticResponse> {
        const response = await this.createDiagnosticV1AnalyzeDiagnosticPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRiskAuditV1AnalyzeRiskAuditPost without sending the request
     */
    async createRiskAuditV1AnalyzeRiskAuditPostRequestOpts(requestParameters: CreateRiskAuditV1AnalyzeRiskAuditPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['riskAuditRequest'] == null) {
            throw new runtime.RequiredError(
                'riskAuditRequest',
                'Required parameter "riskAuditRequest" was null or undefined when calling createRiskAuditV1AnalyzeRiskAuditPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/analyze/riskAudit`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RiskAuditRequestToJSON(requestParameters['riskAuditRequest']),
        };
    }

    /**
     * Compliance Risk Audit — conversation compliance analysis
     */
    async createRiskAuditV1AnalyzeRiskAuditPostRaw(requestParameters: CreateRiskAuditV1AnalyzeRiskAuditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RiskAuditV2Response>> {
        const requestOptions = await this.createRiskAuditV1AnalyzeRiskAuditPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RiskAuditV2ResponseFromJSON(jsonValue));
    }

    /**
     * Compliance Risk Audit — conversation compliance analysis
     */
    async createRiskAuditV1AnalyzeRiskAuditPost(requestParameters: CreateRiskAuditV1AnalyzeRiskAuditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RiskAuditV2Response> {
        const response = await this.createRiskAuditV1AnalyzeRiskAuditPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
