/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateEmailAlertRequest,
    CreateEmailAlertRequestFromJSON,
    CreateEmailAlertRequestToJSON,
} from '../models/CreateEmailAlertRequest';
import {
    type EmailAlertItem,
    EmailAlertItemFromJSON,
    EmailAlertItemToJSON,
} from '../models/EmailAlertItem';
import {
    type EmailAlertListResponse,
    EmailAlertListResponseFromJSON,
    EmailAlertListResponseToJSON,
} from '../models/EmailAlertListResponse';
import {
    type EmailAlertMessageResponse,
    EmailAlertMessageResponseFromJSON,
    EmailAlertMessageResponseToJSON,
} from '../models/EmailAlertMessageResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type UpdateEmailAlertRequest,
    UpdateEmailAlertRequestFromJSON,
    UpdateEmailAlertRequestToJSON,
} from '../models/UpdateEmailAlertRequest';

export interface CreateEmailAlertV1EmailAlertsPostRequest {
    /**
     * 
     */
    createEmailAlertRequest: CreateEmailAlertRequest;
}

export interface DeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest {
    /**
     * 
     */
    alertId: string;
}

export interface ListEmailAlertsV1EmailAlertsGetRequest {
    /**
     * 
     */
    page?: number;
    /**
     * 
     */
    limit?: number;
}

export interface UpdateEmailAlertV1EmailAlertsAlertIdPutRequest {
    /**
     * 
     */
    alertId: string;
    /**
     * 
     */
    updateEmailAlertRequest: UpdateEmailAlertRequest;
}

/**
 * 
 */
export class EmailAlertsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createEmailAlertV1EmailAlertsPost without sending the request
     */
    async createEmailAlertV1EmailAlertsPostRequestOpts(requestParameters: CreateEmailAlertV1EmailAlertsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createEmailAlertRequest'] == null) {
            throw new runtime.RequiredError(
                'createEmailAlertRequest',
                'Required parameter "createEmailAlertRequest" was null or undefined when calling createEmailAlertV1EmailAlertsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/email-alerts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEmailAlertRequestToJSON(requestParameters['createEmailAlertRequest']),
        };
    }

    /**
     * Create email alert
     */
    async createEmailAlertV1EmailAlertsPostRaw(requestParameters: CreateEmailAlertV1EmailAlertsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailAlertItem>> {
        const requestOptions = await this.createEmailAlertV1EmailAlertsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailAlertItemFromJSON(jsonValue));
    }

    /**
     * Create email alert
     */
    async createEmailAlertV1EmailAlertsPost(requestParameters: CreateEmailAlertV1EmailAlertsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailAlertItem> {
        const response = await this.createEmailAlertV1EmailAlertsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEmailAlertV1EmailAlertsAlertIdDelete without sending the request
     */
    async deleteEmailAlertV1EmailAlertsAlertIdDeleteRequestOpts(requestParameters: DeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling deleteEmailAlertV1EmailAlertsAlertIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/email-alerts/{alert_id}`;
        urlPath = urlPath.replace('{alert_id}', encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete email alert
     */
    async deleteEmailAlertV1EmailAlertsAlertIdDeleteRaw(requestParameters: DeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailAlertMessageResponse>> {
        const requestOptions = await this.deleteEmailAlertV1EmailAlertsAlertIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailAlertMessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete email alert
     */
    async deleteEmailAlertV1EmailAlertsAlertIdDelete(requestParameters: DeleteEmailAlertV1EmailAlertsAlertIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailAlertMessageResponse> {
        const response = await this.deleteEmailAlertV1EmailAlertsAlertIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEmailAlertsV1EmailAlertsGet without sending the request
     */
    async listEmailAlertsV1EmailAlertsGetRequestOpts(requestParameters: ListEmailAlertsV1EmailAlertsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/email-alerts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List email alerts
     */
    async listEmailAlertsV1EmailAlertsGetRaw(requestParameters: ListEmailAlertsV1EmailAlertsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailAlertListResponse>> {
        const requestOptions = await this.listEmailAlertsV1EmailAlertsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailAlertListResponseFromJSON(jsonValue));
    }

    /**
     * List email alerts
     */
    async listEmailAlertsV1EmailAlertsGet(requestParameters: ListEmailAlertsV1EmailAlertsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailAlertListResponse> {
        const response = await this.listEmailAlertsV1EmailAlertsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEmailAlertV1EmailAlertsAlertIdPut without sending the request
     */
    async updateEmailAlertV1EmailAlertsAlertIdPutRequestOpts(requestParameters: UpdateEmailAlertV1EmailAlertsAlertIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling updateEmailAlertV1EmailAlertsAlertIdPut().'
            );
        }

        if (requestParameters['updateEmailAlertRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEmailAlertRequest',
                'Required parameter "updateEmailAlertRequest" was null or undefined when calling updateEmailAlertV1EmailAlertsAlertIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/email-alerts/{alert_id}`;
        urlPath = urlPath.replace('{alert_id}', encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEmailAlertRequestToJSON(requestParameters['updateEmailAlertRequest']),
        };
    }

    /**
     * Update email alert
     */
    async updateEmailAlertV1EmailAlertsAlertIdPutRaw(requestParameters: UpdateEmailAlertV1EmailAlertsAlertIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailAlertMessageResponse>> {
        const requestOptions = await this.updateEmailAlertV1EmailAlertsAlertIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailAlertMessageResponseFromJSON(jsonValue));
    }

    /**
     * Update email alert
     */
    async updateEmailAlertV1EmailAlertsAlertIdPut(requestParameters: UpdateEmailAlertV1EmailAlertsAlertIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailAlertMessageResponse> {
        const response = await this.updateEmailAlertV1EmailAlertsAlertIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
