/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type TranscriptionResponse,
    TranscriptionResponseFromJSON,
    TranscriptionResponseToJSON,
} from '../models/TranscriptionResponse';

export interface CreateTranscriptionV1AudioTranscriptionsPostRequest {
    /**
     * 
     */
    file: Blob;
    /**
     * 
     */
    model?: string;
    /**
     * 
     */
    language?: string;
    /**
     * Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency.
     */
    clientReferenceId?: string;
}

/**
 * 
 */
export class SpeechApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTranscriptionV1AudioTranscriptionsPost without sending the request
     */
    async createTranscriptionV1AudioTranscriptionsPostRequestOpts(requestParameters: CreateTranscriptionV1AudioTranscriptionsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling createTranscriptionV1AudioTranscriptionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['model'] != null) {
            formParams.append('model', requestParameters['model'] as any);
        }

        if (requestParameters['language'] != null) {
            formParams.append('language', requestParameters['language'] as any);
        }

        if (requestParameters['clientReferenceId'] != null) {
            formParams.append('client_reference_id', requestParameters['clientReferenceId'] as any);
        }


        let urlPath = `/v1/audio/transcriptions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Transcribe audio to text
     */
    async createTranscriptionV1AudioTranscriptionsPostRaw(requestParameters: CreateTranscriptionV1AudioTranscriptionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranscriptionResponse>> {
        const requestOptions = await this.createTranscriptionV1AudioTranscriptionsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TranscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Transcribe audio to text
     */
    async createTranscriptionV1AudioTranscriptionsPost(requestParameters: CreateTranscriptionV1AudioTranscriptionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranscriptionResponse> {
        const response = await this.createTranscriptionV1AudioTranscriptionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
