/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type UsageByKeyItem,
    UsageByKeyItemFromJSON,
    UsageByKeyItemToJSON,
} from '../models/UsageByKeyItem';
import {
    type UsageLogResponse,
    UsageLogResponseFromJSON,
    UsageLogResponseToJSON,
} from '../models/UsageLogResponse';

export interface GetUsageByKeyV1UsageByKeyGetRequest {
    /**
     * 
     */
    keyId?: string;
}

export interface GetUsageLogV1UsageLogGetRequest {
    /**
     * 
     */
    page?: number;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    apiKeyId?: string;
}

/**
 * 
 */
export class UsageApi extends runtime.BaseAPI {

    /**
     * Creates request options for getUsageByKeyV1UsageByKeyGet without sending the request
     */
    async getUsageByKeyV1UsageByKeyGetRequestOpts(requestParameters: GetUsageByKeyV1UsageByKeyGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['keyId'] != null) {
            queryParameters['key_id'] = requestParameters['keyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/usage/by-key`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Usage By Key
     */
    async getUsageByKeyV1UsageByKeyGetRaw(requestParameters: GetUsageByKeyV1UsageByKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UsageByKeyItem>>> {
        const requestOptions = await this.getUsageByKeyV1UsageByKeyGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsageByKeyItemFromJSON));
    }

    /**
     * Get Usage By Key
     */
    async getUsageByKeyV1UsageByKeyGet(requestParameters: GetUsageByKeyV1UsageByKeyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UsageByKeyItem>> {
        const response = await this.getUsageByKeyV1UsageByKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUsageLogV1UsageLogGet without sending the request
     */
    async getUsageLogV1UsageLogGetRequestOpts(requestParameters: GetUsageLogV1UsageLogGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['apiKeyId'] != null) {
            queryParameters['api_key_id'] = requestParameters['apiKeyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/usage/log`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Usage Log
     */
    async getUsageLogV1UsageLogGetRaw(requestParameters: GetUsageLogV1UsageLogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsageLogResponse>> {
        const requestOptions = await this.getUsageLogV1UsageLogGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsageLogResponseFromJSON(jsonValue));
    }

    /**
     * Get Usage Log
     */
    async getUsageLogV1UsageLogGet(requestParameters: GetUsageLogV1UsageLogGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsageLogResponse> {
        const response = await this.getUsageLogV1UsageLogGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
