/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateWebhookRequest,
    CreateWebhookRequestFromJSON,
    CreateWebhookRequestToJSON,
} from '../models/CreateWebhookRequest';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type MessageResponse,
    MessageResponseFromJSON,
    MessageResponseToJSON,
} from '../models/MessageResponse';
import {
    type UpdateWebhookRequest,
    UpdateWebhookRequestFromJSON,
    UpdateWebhookRequestToJSON,
} from '../models/UpdateWebhookRequest';
import {
    type WebhookItem,
    WebhookItemFromJSON,
    WebhookItemToJSON,
} from '../models/WebhookItem';
import {
    type WebhookListResponse,
    WebhookListResponseFromJSON,
    WebhookListResponseToJSON,
} from '../models/WebhookListResponse';

export interface CreateWebhookV1WebhooksPostRequest {
    /**
     * 
     */
    createWebhookRequest: CreateWebhookRequest;
}

export interface DeleteWebhookV1WebhooksWebhookIdDeleteRequest {
    /**
     * 
     */
    webhookId: string;
}

export interface ListWebhooksV1WebhooksGetRequest {
    /**
     * Pagina (1-indexed)
     */
    page?: number;
    /**
     * Itens por pagina (max 100)
     */
    limit?: number;
}

export interface UpdateWebhookV1WebhooksWebhookIdPutRequest {
    /**
     * 
     */
    webhookId: string;
    /**
     * 
     */
    updateWebhookRequest: UpdateWebhookRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWebhookV1WebhooksPost without sending the request
     */
    async createWebhookV1WebhooksPostRequestOpts(requestParameters: CreateWebhookV1WebhooksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWebhookRequest'] == null) {
            throw new runtime.RequiredError(
                'createWebhookRequest',
                'Required parameter "createWebhookRequest" was null or undefined when calling createWebhookV1WebhooksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookRequestToJSON(requestParameters['createWebhookRequest']),
        };
    }

    /**
     * Creates a subscription for alert events (10 alerts). Payload delivered: WebhookPayload(event, data, timestamp) with HMAC FalaAI-Signature. To verify the origin, recompute HMAC-SHA256 of \"timestamp.body\" with your secret.
     * Create webhook
     */
    async createWebhookV1WebhooksPostRaw(requestParameters: CreateWebhookV1WebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookItem>> {
        const requestOptions = await this.createWebhookV1WebhooksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookItemFromJSON(jsonValue));
    }

    /**
     * Creates a subscription for alert events (10 alerts). Payload delivered: WebhookPayload(event, data, timestamp) with HMAC FalaAI-Signature. To verify the origin, recompute HMAC-SHA256 of \"timestamp.body\" with your secret.
     * Create webhook
     */
    async createWebhookV1WebhooksPost(requestParameters: CreateWebhookV1WebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookItem> {
        const response = await this.createWebhookV1WebhooksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWebhookV1WebhooksWebhookIdDelete without sending the request
     */
    async deleteWebhookV1WebhooksWebhookIdDeleteRequestOpts(requestParameters: DeleteWebhookV1WebhooksWebhookIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['webhookId'] == null) {
            throw new runtime.RequiredError(
                'webhookId',
                'Required parameter "webhookId" was null or undefined when calling deleteWebhookV1WebhooksWebhookIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/{webhook_id}`;
        urlPath = urlPath.replace('{webhook_id}', encodeURIComponent(String(requestParameters['webhookId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a webhook subscription by ID.
     * Delete webhook
     */
    async deleteWebhookV1WebhooksWebhookIdDeleteRaw(requestParameters: DeleteWebhookV1WebhooksWebhookIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const requestOptions = await this.deleteWebhookV1WebhooksWebhookIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a webhook subscription by ID.
     * Delete webhook
     */
    async deleteWebhookV1WebhooksWebhookIdDelete(requestParameters: DeleteWebhookV1WebhooksWebhookIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.deleteWebhookV1WebhooksWebhookIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhooksV1WebhooksGet without sending the request
     */
    async listWebhooksV1WebhooksGetRequestOpts(requestParameters: ListWebhooksV1WebhooksGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists the authenticated user\'s webhooks (10 alerts). Paginated. Includes the URL signature secret (always visible to the owner).
     * List webhooks
     */
    async listWebhooksV1WebhooksGetRaw(requestParameters: ListWebhooksV1WebhooksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookListResponse>> {
        const requestOptions = await this.listWebhooksV1WebhooksGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookListResponseFromJSON(jsonValue));
    }

    /**
     * Lists the authenticated user\'s webhooks (10 alerts). Paginated. Includes the URL signature secret (always visible to the owner).
     * List webhooks
     */
    async listWebhooksV1WebhooksGet(requestParameters: ListWebhooksV1WebhooksGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookListResponse> {
        const response = await this.listWebhooksV1WebhooksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWebhookV1WebhooksWebhookIdPut without sending the request
     */
    async updateWebhookV1WebhooksWebhookIdPutRequestOpts(requestParameters: UpdateWebhookV1WebhooksWebhookIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['webhookId'] == null) {
            throw new runtime.RequiredError(
                'webhookId',
                'Required parameter "webhookId" was null or undefined when calling updateWebhookV1WebhooksWebhookIdPut().'
            );
        }

        if (requestParameters['updateWebhookRequest'] == null) {
            throw new runtime.RequiredError(
                'updateWebhookRequest',
                'Required parameter "updateWebhookRequest" was null or undefined when calling updateWebhookV1WebhooksWebhookIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/webhooks/{webhook_id}`;
        urlPath = urlPath.replace('{webhook_id}', encodeURIComponent(String(requestParameters['webhookId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWebhookRequestToJSON(requestParameters['updateWebhookRequest']),
        };
    }

    /**
     * Updates the webhook\'s name/url/events/retry_enabled/active. Valid events: 10 alerts.
     * Update webhook
     */
    async updateWebhookV1WebhooksWebhookIdPutRaw(requestParameters: UpdateWebhookV1WebhooksWebhookIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const requestOptions = await this.updateWebhookV1WebhooksWebhookIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Updates the webhook\'s name/url/events/retry_enabled/active. Valid events: 10 alerts.
     * Update webhook
     */
    async updateWebhookV1WebhooksWebhookIdPut(requestParameters: UpdateWebhookV1WebhooksWebhookIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.updateWebhookV1WebhooksWebhookIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
