/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioInputMeta
 */
export interface AudioInputMeta {
    /**
     * Exact audio duration sent in seconds
     */
    durationS: number;
    /**
     * Original file format (wav, mp3, ogg, etc)
     */
    originalFormat: string;
    /**
     * Audio codec sent
     */
    codec: string;
    /**
     * Audio sample rate in Hz
     */
    sampleRate: number;
    /**
     * Number of channels (1=mono, 2=stereo)
     */
    channels: number;
}

/**
 * Check if a given object implements the AudioInputMeta interface.
 */
export function instanceOfAudioInputMeta(value: object): value is AudioInputMeta {
    if ((!('durationS' in (value as Record<string, any>)) && !('duration_s' in (value as Record<string, any>))) || ((value as Record<string, any>)['durationS'] === undefined && (value as Record<string, any>)['duration_s'] === undefined)) return false;
    if ((!('originalFormat' in (value as Record<string, any>)) && !('original_format' in (value as Record<string, any>))) || ((value as Record<string, any>)['originalFormat'] === undefined && (value as Record<string, any>)['original_format'] === undefined)) return false;
    if (!('codec' in value) || value['codec'] === undefined) return false;
    if ((!('sampleRate' in (value as Record<string, any>)) && !('sample_rate' in (value as Record<string, any>))) || ((value as Record<string, any>)['sampleRate'] === undefined && (value as Record<string, any>)['sample_rate'] === undefined)) return false;
    if (!('channels' in value) || value['channels'] === undefined) return false;
    return true;
}

export function AudioInputMetaFromJSON(json: any): AudioInputMeta {
    return AudioInputMetaFromJSONTyped(json, false);
}

export function AudioInputMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioInputMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'durationS': json['duration_s'],
        'originalFormat': json['original_format'],
        'codec': json['codec'],
        'sampleRate': json['sample_rate'],
        'channels': json['channels'],
    };
}

export function AudioInputMetaToJSON(json: any): AudioInputMeta {
    return AudioInputMetaToJSONTyped(json, false);
}

export function AudioInputMetaToJSONTyped(value?: AudioInputMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_s': value['durationS'],
        'original_format': value['originalFormat'],
        'codec': value['codec'],
        'sample_rate': value['sampleRate'],
        'channels': value['channels'],
    };
}

