/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioEvent
 */
export interface AudioEvent {
    /**
     * Type of identified audio event. Ex: [riso], [suspiro], [pausa], [tosse]
     */
    event: string;
    /**
     * Start time of audio event in seconds
     */
    startS: number;
    /**
     * End time of audio event in seconds
     */
    endS: number;
    /**
     * Event duration in seconds
     */
    durationS: number;
    /**
     * Formatted timestamp HH:MM:SS.mmm of event start
     */
    formattedTimestamp: string;
}

/**
 * Check if a given object implements the AudioEvent interface.
 */
export function instanceOfAudioEvent(value: object): value is AudioEvent {
    if (!('event' in value) || value['event'] === undefined) return false;
    if ((!('startS' in (value as Record<string, any>)) && !('start_s' in (value as Record<string, any>))) || ((value as Record<string, any>)['startS'] === undefined && (value as Record<string, any>)['start_s'] === undefined)) return false;
    if ((!('endS' in (value as Record<string, any>)) && !('end_s' in (value as Record<string, any>))) || ((value as Record<string, any>)['endS'] === undefined && (value as Record<string, any>)['end_s'] === undefined)) return false;
    if ((!('durationS' in (value as Record<string, any>)) && !('duration_s' in (value as Record<string, any>))) || ((value as Record<string, any>)['durationS'] === undefined && (value as Record<string, any>)['duration_s'] === undefined)) return false;
    if ((!('formattedTimestamp' in (value as Record<string, any>)) && !('formatted_timestamp' in (value as Record<string, any>))) || ((value as Record<string, any>)['formattedTimestamp'] === undefined && (value as Record<string, any>)['formatted_timestamp'] === undefined)) return false;
    return true;
}

export function AudioEventFromJSON(json: any): AudioEvent {
    return AudioEventFromJSONTyped(json, false);
}

export function AudioEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'],
        'startS': json['start_s'],
        'endS': json['end_s'],
        'durationS': json['duration_s'],
        'formattedTimestamp': json['formatted_timestamp'],
    };
}

export function AudioEventToJSON(json: any): AudioEvent {
    return AudioEventToJSONTyped(json, false);
}

export function AudioEventToJSONTyped(value?: AudioEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': value['event'],
        'start_s': value['startS'],
        'end_s': value['endS'],
        'duration_s': value['durationS'],
        'formatted_timestamp': value['formattedTimestamp'],
    };
}

