/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailEvent } from './EmailEvent';
import {
    EmailEventFromJSON,
    EmailEventFromJSONTyped,
    EmailEventToJSON,
    EmailEventToJSONTyped,
} from './EmailEvent';

/**
 * 
 * @export
 * @interface CreateEmailAlertRequest
 */
export interface CreateEmailAlertRequest {
    /**
     * Nome identificador
     */
    name: string;
    /**
     * Email destino
     */
    email: string;
    /**
     * Eventos subscritos
     */
    events: Array<EmailEvent>;
}

/**
 * Check if a given object implements the CreateEmailAlertRequest interface.
 */
export function instanceOfCreateEmailAlertRequest(value: object): value is CreateEmailAlertRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function CreateEmailAlertRequestFromJSON(json: any): CreateEmailAlertRequest {
    return CreateEmailAlertRequestFromJSONTyped(json, false);
}

export function CreateEmailAlertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmailAlertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'events': ((json['events'] as Array<any>).map(EmailEventFromJSON)),
    };
}

export function CreateEmailAlertRequestToJSON(json: any): CreateEmailAlertRequest {
    return CreateEmailAlertRequestToJSONTyped(json, false);
}

export function CreateEmailAlertRequestToJSONTyped(value?: CreateEmailAlertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'events': ((value['events'] as Array<any>).map(EmailEventToJSON)),
    };
}

