/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEvent } from './WebhookEvent';
import {
    WebhookEventFromJSON,
    WebhookEventFromJSONTyped,
    WebhookEventToJSON,
    WebhookEventToJSONTyped,
} from './WebhookEvent';

/**
 * 
 * @export
 * @interface CreateWebhookRequest
 */
export interface CreateWebhookRequest {
    /**
     * Nome identificador do webhook
     */
    name: string;
    /**
     * URL HTTPS que recebera POST com HMAC FalaAI-Signature
     */
    url: string;
    /**
     * Eventos subscritos (10 alertas)
     */
    events: Array<WebhookEvent>;
    /**
     * Retry exponencial 5 tentativas quando true (false=1 tentativa)
     */
    retryEnabled?: boolean;
}

/**
 * Check if a given object implements the CreateWebhookRequest interface.
 */
export function instanceOfCreateWebhookRequest(value: object): value is CreateWebhookRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function CreateWebhookRequestFromJSON(json: any): CreateWebhookRequest {
    return CreateWebhookRequestFromJSONTyped(json, false);
}

export function CreateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'events': ((json['events'] as Array<any>).map(WebhookEventFromJSON)),
        'retryEnabled': json['retry_enabled'] == null ? undefined : json['retry_enabled'],
    };
}

export function CreateWebhookRequestToJSON(json: any): CreateWebhookRequest {
    return CreateWebhookRequestToJSONTyped(json, false);
}

export function CreateWebhookRequestToJSONTyped(value?: CreateWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'events': ((value['events'] as Array<any>).map(WebhookEventToJSON)),
        'retry_enabled': value['retryEnabled'],
    };
}

