/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosticCategoricalAnalysis
 */
export interface DiagnosticCategoricalAnalysis {
    /**
     * Selected value from classification list (used in action, label, sentiment)
     */
    listChoice?: string;
    /**
     * Justification for the choice
     */
    justification?: string;
    /**
     * Verbatim transcript excerpts supporting the analysis
     */
    evidencePhrases?: Array<string>;
}

/**
 * Check if a given object implements the DiagnosticCategoricalAnalysis interface.
 */
export function instanceOfDiagnosticCategoricalAnalysis(value: object): value is DiagnosticCategoricalAnalysis {
    return true;
}

export function DiagnosticCategoricalAnalysisFromJSON(json: any): DiagnosticCategoricalAnalysis {
    return DiagnosticCategoricalAnalysisFromJSONTyped(json, false);
}

export function DiagnosticCategoricalAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticCategoricalAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
        'listChoice': json['list_choice'] == null ? undefined : json['list_choice'],
        'justification': json['justification'] == null ? undefined : json['justification'],
        'evidencePhrases': json['evidence_phrases'] == null ? undefined : json['evidence_phrases'],
    };
}

export function DiagnosticCategoricalAnalysisToJSON(json: any): DiagnosticCategoricalAnalysis {
    return DiagnosticCategoricalAnalysisToJSONTyped(json, false);
}

export function DiagnosticCategoricalAnalysisToJSONTyped(value?: DiagnosticCategoricalAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list_choice': value['listChoice'],
        'justification': value['justification'],
        'evidence_phrases': value['evidencePhrases'],
    };
}

