/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiagnosticAnalysisMap } from './DiagnosticAnalysisMap';
import {
    DiagnosticAnalysisMapFromJSON,
    DiagnosticAnalysisMapFromJSONTyped,
    DiagnosticAnalysisMapToJSON,
    DiagnosticAnalysisMapToJSONTyped,
} from './DiagnosticAnalysisMap';
import type { DiagnosticUsage } from './DiagnosticUsage';
import {
    DiagnosticUsageFromJSON,
    DiagnosticUsageFromJSONTyped,
    DiagnosticUsageToJSON,
    DiagnosticUsageToJSONTyped,
} from './DiagnosticUsage';

/**
 * 
 * @export
 * @interface DiagnosticResponse
 */
export interface DiagnosticResponse {
    /**
     * Unique analysis identifier. Prefix 'di-' + UUID
     */
    id: string;
    /**
     * Language used in the response. E.g.: 'pt-BR', 'en-US', 'es-ES'
     */
    responseLanguage: string;
    /**
     * Object type. Always 'analysis'
     */
    object: string;
    /**
     * The 6 conversation analyses (5 + participants)
     */
    analysis: DiagnosticAnalysisMap;
    /**
     * Usage and processing information
     */
    usage: DiagnosticUsage;
    /**
     * Client-supplied ID echoed verbatim (if provided in request)
     */
    clientReferenceId?: string;
}

/**
 * Check if a given object implements the DiagnosticResponse interface.
 */
export function instanceOfDiagnosticResponse(value: object): value is DiagnosticResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('responseLanguage' in (value as Record<string, any>)) && !('response_language' in (value as Record<string, any>))) || ((value as Record<string, any>)['responseLanguage'] === undefined && (value as Record<string, any>)['response_language'] === undefined)) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('analysis' in value) || value['analysis'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    return true;
}

export function DiagnosticResponseFromJSON(json: any): DiagnosticResponse {
    return DiagnosticResponseFromJSONTyped(json, false);
}

export function DiagnosticResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'responseLanguage': json['response_language'],
        'object': json['object'],
        'analysis': DiagnosticAnalysisMapFromJSON(json['analysis']),
        'usage': DiagnosticUsageFromJSON(json['usage']),
        'clientReferenceId': json['client_reference_id'] == null ? undefined : json['client_reference_id'],
    };
}

export function DiagnosticResponseToJSON(json: any): DiagnosticResponse {
    return DiagnosticResponseToJSONTyped(json, false);
}

export function DiagnosticResponseToJSONTyped(value?: DiagnosticResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'response_language': value['responseLanguage'],
        'object': value['object'],
        'analysis': DiagnosticAnalysisMapToJSON(value['analysis']),
        'usage': DiagnosticUsageToJSON(value['usage']),
        'client_reference_id': value['clientReferenceId'],
    };
}

