/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosticUsage
 */
export interface DiagnosticUsage {
    /**
     * Total characters analyzed
     */
    characters: number;
    /**
     * Credits consumed: max(ceil(chars/500)*3, 3) * 5
     */
    creditsConsumed: number;
    /**
     * Total processing time in milliseconds
     */
    processingMs: number;
}

/**
 * Check if a given object implements the DiagnosticUsage interface.
 */
export function instanceOfDiagnosticUsage(value: object): value is DiagnosticUsage {
    if (!('characters' in value) || value['characters'] === undefined) return false;
    if ((!('creditsConsumed' in (value as Record<string, any>)) && !('credits_consumed' in (value as Record<string, any>))) || ((value as Record<string, any>)['creditsConsumed'] === undefined && (value as Record<string, any>)['credits_consumed'] === undefined)) return false;
    if ((!('processingMs' in (value as Record<string, any>)) && !('processing_ms' in (value as Record<string, any>))) || ((value as Record<string, any>)['processingMs'] === undefined && (value as Record<string, any>)['processing_ms'] === undefined)) return false;
    return true;
}

export function DiagnosticUsageFromJSON(json: any): DiagnosticUsage {
    return DiagnosticUsageFromJSONTyped(json, false);
}

export function DiagnosticUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'characters': json['characters'],
        'creditsConsumed': json['credits_consumed'],
        'processingMs': json['processing_ms'],
    };
}

export function DiagnosticUsageToJSON(json: any): DiagnosticUsage {
    return DiagnosticUsageToJSONTyped(json, false);
}

export function DiagnosticUsageToJSONTyped(value?: DiagnosticUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'characters': value['characters'],
        'credits_consumed': value['creditsConsumed'],
        'processing_ms': value['processingMs'],
    };
}

