/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiagnosticCategoricalAnalysis } from './DiagnosticCategoricalAnalysis';
import {
    DiagnosticCategoricalAnalysisFromJSON,
    DiagnosticCategoricalAnalysisFromJSONTyped,
    DiagnosticCategoricalAnalysisToJSON,
    DiagnosticCategoricalAnalysisToJSONTyped,
} from './DiagnosticCategoricalAnalysis';
import type { ParticipantDiagnostic } from './ParticipantDiagnostic';
import {
    ParticipantDiagnosticFromJSON,
    ParticipantDiagnosticFromJSONTyped,
    ParticipantDiagnosticToJSON,
    ParticipantDiagnosticToJSONTyped,
} from './ParticipantDiagnostic';
import type { DiagnosticTextAnalysis } from './DiagnosticTextAnalysis';
import {
    DiagnosticTextAnalysisFromJSON,
    DiagnosticTextAnalysisFromJSONTyped,
    DiagnosticTextAnalysisToJSON,
    DiagnosticTextAnalysisToJSONTyped,
} from './DiagnosticTextAnalysis';

/**
 * 
 * @export
 * @interface DiagnosticAnalysisMap
 */
export interface DiagnosticAnalysisMap {
    /**
     * Detailed conversation summary
     */
    dialogueSummary: DiagnosticTextAnalysis;
    /**
     * Initial contact reason
     */
    contactReason: DiagnosticTextAnalysis;
    /**
     * Action taken / resolution
     */
    identifiedAction: DiagnosticCategoricalAnalysis;
    /**
     * Theme classification
     */
    identifiedLabel: DiagnosticCategoricalAnalysis;
    /**
     * Predominant sentiment
     */
    sentiment: DiagnosticCategoricalAnalysis;
    /**
     * Identified participants and roles (same field names as auditoria)
     */
    participantsIdentified?: Array<ParticipantDiagnostic>;
}

/**
 * Check if a given object implements the DiagnosticAnalysisMap interface.
 */
export function instanceOfDiagnosticAnalysisMap(value: object): value is DiagnosticAnalysisMap {
    if ((!('dialogueSummary' in (value as Record<string, any>)) && !('dialogue_summary' in (value as Record<string, any>))) || ((value as Record<string, any>)['dialogueSummary'] === undefined && (value as Record<string, any>)['dialogue_summary'] === undefined)) return false;
    if ((!('contactReason' in (value as Record<string, any>)) && !('contact_reason' in (value as Record<string, any>))) || ((value as Record<string, any>)['contactReason'] === undefined && (value as Record<string, any>)['contact_reason'] === undefined)) return false;
    if ((!('identifiedAction' in (value as Record<string, any>)) && !('identified_action' in (value as Record<string, any>))) || ((value as Record<string, any>)['identifiedAction'] === undefined && (value as Record<string, any>)['identified_action'] === undefined)) return false;
    if ((!('identifiedLabel' in (value as Record<string, any>)) && !('identified_label' in (value as Record<string, any>))) || ((value as Record<string, any>)['identifiedLabel'] === undefined && (value as Record<string, any>)['identified_label'] === undefined)) return false;
    if (!('sentiment' in value) || value['sentiment'] === undefined) return false;
    return true;
}

export function DiagnosticAnalysisMapFromJSON(json: any): DiagnosticAnalysisMap {
    return DiagnosticAnalysisMapFromJSONTyped(json, false);
}

export function DiagnosticAnalysisMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticAnalysisMap {
    if (json == null) {
        return json;
    }
    return {
        
        'dialogueSummary': DiagnosticTextAnalysisFromJSON(json['dialogue_summary']),
        'contactReason': DiagnosticTextAnalysisFromJSON(json['contact_reason']),
        'identifiedAction': DiagnosticCategoricalAnalysisFromJSON(json['identified_action']),
        'identifiedLabel': DiagnosticCategoricalAnalysisFromJSON(json['identified_label']),
        'sentiment': DiagnosticCategoricalAnalysisFromJSON(json['sentiment']),
        'participantsIdentified': json['participants_identified'] == null ? undefined : ((json['participants_identified'] as Array<any>).map(ParticipantDiagnosticFromJSON)),
    };
}

export function DiagnosticAnalysisMapToJSON(json: any): DiagnosticAnalysisMap {
    return DiagnosticAnalysisMapToJSONTyped(json, false);
}

export function DiagnosticAnalysisMapToJSONTyped(value?: DiagnosticAnalysisMap | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dialogue_summary': DiagnosticTextAnalysisToJSON(value['dialogueSummary']),
        'contact_reason': DiagnosticTextAnalysisToJSON(value['contactReason']),
        'identified_action': DiagnosticCategoricalAnalysisToJSON(value['identifiedAction']),
        'identified_label': DiagnosticCategoricalAnalysisToJSON(value['identifiedLabel']),
        'sentiment': DiagnosticCategoricalAnalysisToJSON(value['sentiment']),
        'participants_identified': value['participantsIdentified'] == null ? undefined : ((value['participantsIdentified'] as Array<any>).map(ParticipantDiagnosticToJSON)),
    };
}

