/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosticTextAnalysis
 */
export interface DiagnosticTextAnalysis {
    /**
     * Explanatory text (used in summary and reason)
     */
    explanation?: string;
}

/**
 * Check if a given object implements the DiagnosticTextAnalysis interface.
 */
export function instanceOfDiagnosticTextAnalysis(value: object): value is DiagnosticTextAnalysis {
    return true;
}

export function DiagnosticTextAnalysisFromJSON(json: any): DiagnosticTextAnalysis {
    return DiagnosticTextAnalysisFromJSONTyped(json, false);
}

export function DiagnosticTextAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticTextAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
        'explanation': json['explanation'] == null ? undefined : json['explanation'],
    };
}

export function DiagnosticTextAnalysisToJSON(json: any): DiagnosticTextAnalysis {
    return DiagnosticTextAnalysisToJSONTyped(json, false);
}

export function DiagnosticTextAnalysisToJSONTyped(value?: DiagnosticTextAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'explanation': value['explanation'],
    };
}

