/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosticParticipant
 */
export interface DiagnosticParticipant {
    /**
     * Exact speaker label from the dialog (e.g. 'Speaker 1')
     */
    interlocutor: string;
    /**
     * Participant name (optional)
     */
    name?: string;
    /**
     * agent | client | bot
     */
    role: DiagnosticParticipantRoleEnum;
}


/**
 * @export
 */
export const DiagnosticParticipantRoleEnum = {
    Agent: 'agent',
    Client: 'client',
    Bot: 'bot',
} as const;
export type DiagnosticParticipantRoleEnum = typeof DiagnosticParticipantRoleEnum[keyof typeof DiagnosticParticipantRoleEnum];


/**
 * Check if a given object implements the DiagnosticParticipant interface.
 */
export function instanceOfDiagnosticParticipant(value: object): value is DiagnosticParticipant {
    if (!('interlocutor' in value) || value['interlocutor'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function DiagnosticParticipantFromJSON(json: any): DiagnosticParticipant {
    return DiagnosticParticipantFromJSONTyped(json, false);
}

export function DiagnosticParticipantFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticParticipant {
    if (json == null) {
        return json;
    }
    return {
        
        'interlocutor': json['interlocutor'],
        'name': json['name'] == null ? undefined : json['name'],
        'role': json['role'],
    };
}

export function DiagnosticParticipantToJSON(json: any): DiagnosticParticipant {
    return DiagnosticParticipantToJSONTyped(json, false);
}

export function DiagnosticParticipantToJSONTyped(value?: DiagnosticParticipant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interlocutor': value['interlocutor'],
        'name': value['name'],
        'role': value['role'],
    };
}

