/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosticAudioEvent
 */
export interface DiagnosticAudioEvent {
    /**
     * Audio event type. E.g.: [laughter], [sigh]
     */
    event: string;
    /**
     * Start time in seconds
     */
    startS?: number;
    /**
     * End time in seconds
     */
    endS?: number;
    /**
     * Duration in seconds
     */
    durationS?: number;
    /**
     * Formatted timestamp (HH:MM:SS.ms)
     */
    formattedTimestamp?: string;
}

/**
 * Check if a given object implements the DiagnosticAudioEvent interface.
 */
export function instanceOfDiagnosticAudioEvent(value: object): value is DiagnosticAudioEvent {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function DiagnosticAudioEventFromJSON(json: any): DiagnosticAudioEvent {
    return DiagnosticAudioEventFromJSONTyped(json, false);
}

export function DiagnosticAudioEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticAudioEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'],
        'startS': json['start_s'] == null ? undefined : json['start_s'],
        'endS': json['end_s'] == null ? undefined : json['end_s'],
        'durationS': json['duration_s'] == null ? undefined : json['duration_s'],
        'formattedTimestamp': json['formatted_timestamp'] == null ? undefined : json['formatted_timestamp'],
    };
}

export function DiagnosticAudioEventToJSON(json: any): DiagnosticAudioEvent {
    return DiagnosticAudioEventToJSONTyped(json, false);
}

export function DiagnosticAudioEventToJSONTyped(value?: DiagnosticAudioEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': value['event'],
        'start_s': value['startS'],
        'end_s': value['endS'],
        'duration_s': value['durationS'],
        'formatted_timestamp': value['formattedTimestamp'],
    };
}

