/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiagnosticAudioEvent } from './DiagnosticAudioEvent';
import {
    DiagnosticAudioEventFromJSON,
    DiagnosticAudioEventFromJSONTyped,
    DiagnosticAudioEventToJSON,
    DiagnosticAudioEventToJSONTyped,
} from './DiagnosticAudioEvent';
import type { DiagnosticParticipant } from './DiagnosticParticipant';
import {
    DiagnosticParticipantFromJSON,
    DiagnosticParticipantFromJSONTyped,
    DiagnosticParticipantToJSON,
    DiagnosticParticipantToJSONTyped,
} from './DiagnosticParticipant';

/**
 * 
 * @export
 * @interface DiagnosticRequest
 */
export interface DiagnosticRequest {
    /**
     * Analysis model. Always 'falaai-diagnostic-1'
     */
    model?: string;
    /**
     * Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters
     */
    text?: string;
    /**
     * Diarized transcript with speaker turns. PRIMARY source. At least one of 'dialog' or 'text' required. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters
     */
    dialog?: string;
    /**
     * Detected audio events with timestamps (required when using dialog)
     */
    audioEvents?: Array<DiagnosticAudioEvent>;
    /**
     * Transcript language. Required. Accepted: en-US, pt-BR, es-ES, es-MX, fr-FR, de-DE, it-IT, pt-PT, zh-CN, ja-JP, ko-KR, ar-SA, hi-IN, ru-RU, id-ID, tr-TR, nl-NL, pl-PL, vi-VN, th-TH, en-GB
     */
    language: string;
    /**
     * Language for the analysis results (labels, categories, levels). Can differ from 'language' (input). If omitted, uses 'language'. Accepted: en-US, es-ES, es-MX, pt-BR, fr-FR, de-DE, it-IT, pt-PT, zh-CN, ja-JP, ko-KR, ar-SA, hi-IN, ru-RU, id-ID, tr-TR, nl-NL, pl-PL, vi-VN, th-TH, en-GB.
     */
    responseLanguage?: string;
    /**
     * Total audio duration in seconds. Required. Max 3h (10800s).
     */
    durationSeconds: number;
    /**
     * Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
     */
    clientReferenceId?: string;
    /**
     * Who originated the call. inbound=client called, outbound=company called. If omitted, the LLM infers from context.
     */
    callDirection?: DiagnosticRequestCallDirectionEnum;
    /**
     * Explicit participant roles. If omitted, the LLM infers from the dialog. When provided, used as ground truth (no inference) and echoed in analysis.participants_identified.
     */
    participants?: Array<DiagnosticParticipant>;
}


/**
 * @export
 */
export const DiagnosticRequestCallDirectionEnum = {
    Inbound: 'inbound',
    Outbound: 'outbound',
} as const;
export type DiagnosticRequestCallDirectionEnum = typeof DiagnosticRequestCallDirectionEnum[keyof typeof DiagnosticRequestCallDirectionEnum];


/**
 * Check if a given object implements the DiagnosticRequest interface.
 */
export function instanceOfDiagnosticRequest(value: object): value is DiagnosticRequest {
    if (!('language' in value) || value['language'] === undefined) return false;
    if ((!('durationSeconds' in (value as Record<string, any>)) && !('duration_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['durationSeconds'] === undefined && (value as Record<string, any>)['duration_seconds'] === undefined)) return false;
    return true;
}

export function DiagnosticRequestFromJSON(json: any): DiagnosticRequest {
    return DiagnosticRequestFromJSONTyped(json, false);
}

export function DiagnosticRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosticRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'text': json['text'] == null ? undefined : json['text'],
        'dialog': json['dialog'] == null ? undefined : json['dialog'],
        'audioEvents': json['audio_events'] == null ? undefined : ((json['audio_events'] as Array<any>).map(DiagnosticAudioEventFromJSON)),
        'language': json['language'],
        'responseLanguage': json['response_language'] == null ? undefined : json['response_language'],
        'durationSeconds': json['duration_seconds'],
        'clientReferenceId': json['client_reference_id'] == null ? undefined : json['client_reference_id'],
        'callDirection': json['call_direction'] == null ? undefined : json['call_direction'],
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(DiagnosticParticipantFromJSON)),
    };
}

export function DiagnosticRequestToJSON(json: any): DiagnosticRequest {
    return DiagnosticRequestToJSONTyped(json, false);
}

export function DiagnosticRequestToJSONTyped(value?: DiagnosticRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'text': value['text'],
        'dialog': value['dialog'],
        'audio_events': value['audioEvents'] == null ? undefined : ((value['audioEvents'] as Array<any>).map(DiagnosticAudioEventToJSON)),
        'language': value['language'],
        'response_language': value['responseLanguage'],
        'duration_seconds': value['durationSeconds'],
        'client_reference_id': value['clientReferenceId'],
        'call_direction': value['callDirection'],
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(DiagnosticParticipantToJSON)),
    };
}

