/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAlertMessageResponse
 */
export interface EmailAlertMessageResponse {
    /**
     * Operation result message
     */
    message: string;
}

/**
 * Check if a given object implements the EmailAlertMessageResponse interface.
 */
export function instanceOfEmailAlertMessageResponse(value: object): value is EmailAlertMessageResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function EmailAlertMessageResponseFromJSON(json: any): EmailAlertMessageResponse {
    return EmailAlertMessageResponseFromJSONTyped(json, false);
}

export function EmailAlertMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAlertMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function EmailAlertMessageResponseToJSON(json: any): EmailAlertMessageResponse {
    return EmailAlertMessageResponseToJSONTyped(json, false);
}

export function EmailAlertMessageResponseToJSONTyped(value?: EmailAlertMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

