/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EmailEvent = {
    SubscriptionCreated: 'subscription.created',
    AvulsoCompleted: 'avulso.completed',
    SubscriptionUpgraded: 'subscription.upgraded',
    SubscriptionDowngraded: 'subscription.downgraded',
    SubscriptionCanceled: 'subscription.canceled',
    CreditsLow: 'credits.low',
    CreditsExhausted: 'credits.exhausted',
    SubscriptionRenewed: 'subscription.renewed',
    PaymentFailed: 'payment.failed',
} as const;
export type EmailEvent = typeof EmailEvent[keyof typeof EmailEvent];


export function instanceOfEmailEvent(value: any): boolean {
    for (const key in EmailEvent) {
        if (Object.prototype.hasOwnProperty.call(EmailEvent, key)) {
            if (EmailEvent[key as keyof typeof EmailEvent] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EmailEventFromJSON(json: any): EmailEvent {
    return EmailEventFromJSONTyped(json, false);
}

export function EmailEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailEvent {
    return json as EmailEvent;
}

export function EmailEventToJSON(value?: EmailEvent | null): any {
    return value as any;
}

export function EmailEventToJSONTyped(value: any, ignoreDiscriminator: boolean): EmailEvent {
    return value as EmailEvent;
}

