/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAlertItem
 */
export interface EmailAlertItem {
    /**
     * Email alert id
     */
    id: string;
    /**
     * Owner user id
     */
    userId: string;
    /**
     * Email alert name
     */
    name: string;
    /**
     * Destination email
     */
    email: string;
    /**
     * Subscribed events
     */
    events: Array<string>;
    /**
     * Is active
     */
    active: boolean;
    /**
     * ISO 8601 created
     */
    createdAt: string;
    /**
     * ISO 8601 updated
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the EmailAlertItem interface.
 */
export function instanceOfEmailAlertItem(value: object): value is EmailAlertItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('userId' in (value as Record<string, any>)) && !('user_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['userId'] === undefined && (value as Record<string, any>)['user_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function EmailAlertItemFromJSON(json: any): EmailAlertItem {
    return EmailAlertItemFromJSONTyped(json, false);
}

export function EmailAlertItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAlertItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'name': json['name'],
        'email': json['email'],
        'events': json['events'],
        'active': json['active'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function EmailAlertItemToJSON(json: any): EmailAlertItem {
    return EmailAlertItemToJSONTyped(json, false);
}

export function EmailAlertItemToJSONTyped(value?: EmailAlertItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'name': value['name'],
        'email': value['email'],
        'events': value['events'],
        'active': value['active'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

