/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailAlertItem } from './EmailAlertItem';
import {
    EmailAlertItemFromJSON,
    EmailAlertItemFromJSONTyped,
    EmailAlertItemToJSON,
    EmailAlertItemToJSONTyped,
} from './EmailAlertItem';

/**
 * 
 * @export
 * @interface EmailAlertListResponse
 */
export interface EmailAlertListResponse {
    /**
     * 
     */
    data: Array<EmailAlertItem>;
    /**
     * 
     */
    page: number;
    /**
     * 
     */
    limit: number;
}

/**
 * Check if a given object implements the EmailAlertListResponse interface.
 */
export function instanceOfEmailAlertListResponse(value: object): value is EmailAlertListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function EmailAlertListResponseFromJSON(json: any): EmailAlertListResponse {
    return EmailAlertListResponseFromJSONTyped(json, false);
}

export function EmailAlertListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAlertListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(EmailAlertItemFromJSON)),
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function EmailAlertListResponseToJSON(json: any): EmailAlertListResponse {
    return EmailAlertListResponseToJSONTyped(json, false);
}

export function EmailAlertListResponseToJSONTyped(value?: EmailAlertListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(EmailAlertItemToJSON)),
        'page': value['page'],
        'limit': value['limit'],
    };
}

