/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * Overall API status
     */
    status: string;
    /**
     * Current API version
     */
    version: string;
    /**
     * Uptime in seconds
     */
    uptimeSeconds: number;
    /**
     * Database connection status
     */
    database: boolean;
    /**
     * Development phase
     */
    phase: string;
    /**
     * Expected public launch date
     */
    launchDate: string;
}

/**
 * Check if a given object implements the HealthResponse interface.
 */
export function instanceOfHealthResponse(value: object): value is HealthResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if ((!('uptimeSeconds' in (value as Record<string, any>)) && !('uptime_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['uptimeSeconds'] === undefined && (value as Record<string, any>)['uptime_seconds'] === undefined)) return false;
    if (!('database' in value) || value['database'] === undefined) return false;
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if ((!('launchDate' in (value as Record<string, any>)) && !('launch_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['launchDate'] === undefined && (value as Record<string, any>)['launch_date'] === undefined)) return false;
    return true;
}

export function HealthResponseFromJSON(json: any): HealthResponse {
    return HealthResponseFromJSONTyped(json, false);
}

export function HealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'version': json['version'],
        'uptimeSeconds': json['uptime_seconds'],
        'database': json['database'],
        'phase': json['phase'],
        'launchDate': json['launch_date'],
    };
}

export function HealthResponseToJSON(json: any): HealthResponse {
    return HealthResponseToJSONTyped(json, false);
}

export function HealthResponseToJSONTyped(value?: HealthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'version': value['version'],
        'uptime_seconds': value['uptimeSeconds'],
        'database': value['database'],
        'phase': value['phase'],
        'launch_date': value['launchDate'],
    };
}

