/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParticipantDiagnostic
 */
export interface ParticipantDiagnostic {
    /**
     * Exact speaker label from the dialog (e.g. 'Speaker 1')
     */
    interlocutor: string;
    /**
     * Role: agent | client | bot | agent_requester | agent_custodian
     */
    role: string;
    /**
     * Participant name if mentioned in the dialogue
     */
    name?: string;
    /**
     * high | medium | low
     */
    confidence?: string;
    /**
     * Exact verbatim quote supporting the role (no timestamps)
     */
    evidence?: string;
}

/**
 * Check if a given object implements the ParticipantDiagnostic interface.
 */
export function instanceOfParticipantDiagnostic(value: object): value is ParticipantDiagnostic {
    if (!('interlocutor' in value) || value['interlocutor'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ParticipantDiagnosticFromJSON(json: any): ParticipantDiagnostic {
    return ParticipantDiagnosticFromJSONTyped(json, false);
}

export function ParticipantDiagnosticFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParticipantDiagnostic {
    if (json == null) {
        return json;
    }
    return {
        
        'interlocutor': json['interlocutor'],
        'role': json['role'],
        'name': json['name'] == null ? undefined : json['name'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'evidence': json['evidence'] == null ? undefined : json['evidence'],
    };
}

export function ParticipantDiagnosticToJSON(json: any): ParticipantDiagnostic {
    return ParticipantDiagnosticToJSONTyped(json, false);
}

export function ParticipantDiagnosticToJSONTyped(value?: ParticipantDiagnostic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interlocutor': value['interlocutor'],
        'role': value['role'],
        'name': value['name'],
        'confidence': value['confidence'],
        'evidence': value['evidence'],
    };
}

