/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Participant
 */
export interface Participant {
    /**
     * Exact identifier as used in dialog (e.g. 'Interlocutor 1', 'Antonio')
     */
    interlocutor: string;
    /**
     * Participant name (humanizes report, does not affect logic)
     */
    name?: string;
    /**
     * Role: agent (human operator), client (customer), bot (IVR/AI)
     */
    role: ParticipantRoleEnum;
}


/**
 * @export
 */
export const ParticipantRoleEnum = {
    Agent: 'agent',
    Client: 'client',
    Bot: 'bot',
} as const;
export type ParticipantRoleEnum = typeof ParticipantRoleEnum[keyof typeof ParticipantRoleEnum];


/**
 * Check if a given object implements the Participant interface.
 */
export function instanceOfParticipant(value: object): value is Participant {
    if (!('interlocutor' in value) || value['interlocutor'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ParticipantFromJSON(json: any): Participant {
    return ParticipantFromJSONTyped(json, false);
}

export function ParticipantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Participant {
    if (json == null) {
        return json;
    }
    return {
        
        'interlocutor': json['interlocutor'],
        'name': json['name'] == null ? undefined : json['name'],
        'role': json['role'],
    };
}

export function ParticipantToJSON(json: any): Participant {
    return ParticipantToJSONTyped(json, false);
}

export function ParticipantToJSONTyped(value?: Participant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interlocutor': value['interlocutor'],
        'name': value['name'],
        'role': value['role'],
    };
}

