/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditParticipantV2
 */
export interface RiskAuditParticipantV2 {
    /**
     * Speaker label
     */
    interlocutor?: string;
    /**
     * Participant name
     */
    name?: string;
    /**
     * Role (agent/client/bot/unknown)
     */
    role?: string;
    /**
     * Role inference confidence (high/medium/low)
     */
    confidence?: string;
    /**
     * Role source (input/inferred)
     */
    source?: string;
    /**
     * Role inference evidence
     */
    evidence?: string;
}

/**
 * Check if a given object implements the RiskAuditParticipantV2 interface.
 */
export function instanceOfRiskAuditParticipantV2(value: object): value is RiskAuditParticipantV2 {
    return true;
}

export function RiskAuditParticipantV2FromJSON(json: any): RiskAuditParticipantV2 {
    return RiskAuditParticipantV2FromJSONTyped(json, false);
}

export function RiskAuditParticipantV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditParticipantV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'interlocutor': json['interlocutor'] == null ? undefined : json['interlocutor'],
        'name': json['name'] == null ? undefined : json['name'],
        'role': json['role'] == null ? undefined : json['role'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'source': json['source'] == null ? undefined : json['source'],
        'evidence': json['evidence'] == null ? undefined : json['evidence'],
    };
}

export function RiskAuditParticipantV2ToJSON(json: any): RiskAuditParticipantV2 {
    return RiskAuditParticipantV2ToJSONTyped(json, false);
}

export function RiskAuditParticipantV2ToJSONTyped(value?: RiskAuditParticipantV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interlocutor': value['interlocutor'],
        'name': value['name'],
        'role': value['role'],
        'confidence': value['confidence'],
        'source': value['source'],
        'evidence': value['evidence'],
    };
}

