/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditIndexerV2
 */
export interface RiskAuditIndexerV2 {
    /**
     * Suggested terms for bank
     */
    suggestedTermsForBank?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the RiskAuditIndexerV2 interface.
 */
export function instanceOfRiskAuditIndexerV2(value: object): value is RiskAuditIndexerV2 {
    return true;
}

export function RiskAuditIndexerV2FromJSON(json: any): RiskAuditIndexerV2 {
    return RiskAuditIndexerV2FromJSONTyped(json, false);
}

export function RiskAuditIndexerV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditIndexerV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestedTermsForBank': json['suggested_terms_for_bank'] == null ? undefined : json['suggested_terms_for_bank'],
    };
}

export function RiskAuditIndexerV2ToJSON(json: any): RiskAuditIndexerV2 {
    return RiskAuditIndexerV2ToJSONTyped(json, false);
}

export function RiskAuditIndexerV2ToJSONTyped(value?: RiskAuditIndexerV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggested_terms_for_bank': value['suggestedTermsForBank'],
    };
}

