/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditAuditDecisionsV2
 */
export interface RiskAuditAuditDecisionsV2 {
    /**
     * Risk origin
     */
    riskOrigin?: string;
    /**
     * Has zero-tolerance violation
     */
    hasZeroToleranceViolation?: boolean;
    /**
     * Deterministic validator changes
     */
    deterministicValidatorChanges?: Array<any>;
}

/**
 * Check if a given object implements the RiskAuditAuditDecisionsV2 interface.
 */
export function instanceOfRiskAuditAuditDecisionsV2(value: object): value is RiskAuditAuditDecisionsV2 {
    return true;
}

export function RiskAuditAuditDecisionsV2FromJSON(json: any): RiskAuditAuditDecisionsV2 {
    return RiskAuditAuditDecisionsV2FromJSONTyped(json, false);
}

export function RiskAuditAuditDecisionsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditAuditDecisionsV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'riskOrigin': json['risk_origin'] == null ? undefined : json['risk_origin'],
        'hasZeroToleranceViolation': json['has_zero_tolerance_violation'] == null ? undefined : json['has_zero_tolerance_violation'],
        'deterministicValidatorChanges': json['deterministic_validator_changes'] == null ? undefined : json['deterministic_validator_changes'],
    };
}

export function RiskAuditAuditDecisionsV2ToJSON(json: any): RiskAuditAuditDecisionsV2 {
    return RiskAuditAuditDecisionsV2ToJSONTyped(json, false);
}

export function RiskAuditAuditDecisionsV2ToJSONTyped(value?: RiskAuditAuditDecisionsV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'risk_origin': value['riskOrigin'],
        'has_zero_tolerance_violation': value['hasZeroToleranceViolation'],
        'deterministic_validator_changes': value['deterministicValidatorChanges'],
    };
}

