/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditAnalysisV2
 */
export interface RiskAuditAnalysisV2 {
    /**
     * Global metrics
     */
    globalMetrics?: { [key: string]: any; };
    /**
     * Final analysis
     */
    finalAnalysis?: { [key: string]: any; };
    /**
     * Frameworks (COPC/ISO/Kirkpatrick/CES)
     */
    frameworks?: { [key: string]: any; };
}

/**
 * Check if a given object implements the RiskAuditAnalysisV2 interface.
 */
export function instanceOfRiskAuditAnalysisV2(value: object): value is RiskAuditAnalysisV2 {
    return true;
}

export function RiskAuditAnalysisV2FromJSON(json: any): RiskAuditAnalysisV2 {
    return RiskAuditAnalysisV2FromJSONTyped(json, false);
}

export function RiskAuditAnalysisV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditAnalysisV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'globalMetrics': json['global_metrics'] == null ? undefined : json['global_metrics'],
        'finalAnalysis': json['final_analysis'] == null ? undefined : json['final_analysis'],
        'frameworks': json['frameworks'] == null ? undefined : json['frameworks'],
    };
}

export function RiskAuditAnalysisV2ToJSON(json: any): RiskAuditAnalysisV2 {
    return RiskAuditAnalysisV2ToJSONTyped(json, false);
}

export function RiskAuditAnalysisV2ToJSONTyped(value?: RiskAuditAnalysisV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'global_metrics': value['globalMetrics'],
        'final_analysis': value['finalAnalysis'],
        'frameworks': value['frameworks'],
    };
}

