/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskAuditV2 } from './RiskAuditV2';
import {
    RiskAuditV2FromJSON,
    RiskAuditV2FromJSONTyped,
    RiskAuditV2ToJSON,
    RiskAuditV2ToJSONTyped,
} from './RiskAuditV2';

/**
 * 
 * @export
 * @interface RiskAuditV2Response
 */
export interface RiskAuditV2Response {
    /**
     * Public response V2 — always returned
     */
    response: RiskAuditV2;
}

/**
 * Check if a given object implements the RiskAuditV2Response interface.
 */
export function instanceOfRiskAuditV2Response(value: object): value is RiskAuditV2Response {
    if (!('response' in value) || value['response'] === undefined) return false;
    return true;
}

export function RiskAuditV2ResponseFromJSON(json: any): RiskAuditV2Response {
    return RiskAuditV2ResponseFromJSONTyped(json, false);
}

export function RiskAuditV2ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditV2Response {
    if (json == null) {
        return json;
    }
    return {
        
        'response': RiskAuditV2FromJSON(json['response']),
    };
}

export function RiskAuditV2ResponseToJSON(json: any): RiskAuditV2Response {
    return RiskAuditV2ResponseToJSONTyped(json, false);
}

export function RiskAuditV2ResponseToJSONTyped(value?: RiskAuditV2Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': RiskAuditV2ToJSON(value['response']),
    };
}

