/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditSummaryV2
 */
export interface RiskAuditSummaryV2 {
    /**
     * Total turns
     */
    totalTurns?: number;
    /**
     * Total calibrated detections
     */
    totalCalibrated?: number;
    /**
     * Active detections
     */
    active?: number;
    /**
     * Tolerated detections
     */
    tolerated?: number;
    /**
     * Blocked detections
     */
    blocked?: number;
    /**
     * Audio events used
     */
    audioEventsUsed?: number;
    /**
     * Audio events aggravated
     */
    audioEventsAggravated?: number;
    /**
     * MAC audio applied
     */
    macAudioApplied?: any | null;
    /**
     * MVAD applied
     */
    mvadApplied?: any | null;
    /**
     * Total participants
     */
    totalParticipants?: number;
    /**
     * Total agents
     */
    totalAgents?: number;
    /**
     * Total clients
     */
    totalClients?: number;
    /**
     * Total bots
     */
    totalBots?: number;
    /**
     * Total unknown
     */
    totalUnknown?: number;
    /**
     * Client risk alerts count
     */
    clientRiskAlertsCount?: number;
    /**
     * Client behavior alerts count
     */
    clientBehaviorAlertsCount?: number;
}

/**
 * Check if a given object implements the RiskAuditSummaryV2 interface.
 */
export function instanceOfRiskAuditSummaryV2(value: object): value is RiskAuditSummaryV2 {
    return true;
}

export function RiskAuditSummaryV2FromJSON(json: any): RiskAuditSummaryV2 {
    return RiskAuditSummaryV2FromJSONTyped(json, false);
}

export function RiskAuditSummaryV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditSummaryV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTurns': json['total_turns'] == null ? undefined : json['total_turns'],
        'totalCalibrated': json['total_calibrated'] == null ? undefined : json['total_calibrated'],
        'active': json['active'] == null ? undefined : json['active'],
        'tolerated': json['tolerated'] == null ? undefined : json['tolerated'],
        'blocked': json['blocked'] == null ? undefined : json['blocked'],
        'audioEventsUsed': json['audio_events_used'] == null ? undefined : json['audio_events_used'],
        'audioEventsAggravated': json['audio_events_aggravated'] == null ? undefined : json['audio_events_aggravated'],
        'macAudioApplied': json['mac_audio_applied'] === undefined ? undefined : json['mac_audio_applied'] === null ? null : json['mac_audio_applied'],
        'mvadApplied': json['mvad_applied'] === undefined ? undefined : json['mvad_applied'] === null ? null : json['mvad_applied'],
        'totalParticipants': json['total_participants'] == null ? undefined : json['total_participants'],
        'totalAgents': json['total_agents'] == null ? undefined : json['total_agents'],
        'totalClients': json['total_clients'] == null ? undefined : json['total_clients'],
        'totalBots': json['total_bots'] == null ? undefined : json['total_bots'],
        'totalUnknown': json['total_unknown'] == null ? undefined : json['total_unknown'],
        'clientRiskAlertsCount': json['client_risk_alerts_count'] == null ? undefined : json['client_risk_alerts_count'],
        'clientBehaviorAlertsCount': json['client_behavior_alerts_count'] == null ? undefined : json['client_behavior_alerts_count'],
    };
}

export function RiskAuditSummaryV2ToJSON(json: any): RiskAuditSummaryV2 {
    return RiskAuditSummaryV2ToJSONTyped(json, false);
}

export function RiskAuditSummaryV2ToJSONTyped(value?: RiskAuditSummaryV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_turns': value['totalTurns'],
        'total_calibrated': value['totalCalibrated'],
        'active': value['active'],
        'tolerated': value['tolerated'],
        'blocked': value['blocked'],
        'audio_events_used': value['audioEventsUsed'],
        'audio_events_aggravated': value['audioEventsAggravated'],
        'mac_audio_applied': value['macAudioApplied'],
        'mvad_applied': value['mvadApplied'],
        'total_participants': value['totalParticipants'],
        'total_agents': value['totalAgents'],
        'total_clients': value['totalClients'],
        'total_bots': value['totalBots'],
        'total_unknown': value['totalUnknown'],
        'client_risk_alerts_count': value['clientRiskAlertsCount'],
        'client_behavior_alerts_count': value['clientBehaviorAlertsCount'],
    };
}

