/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskAuditUsageV2 } from './RiskAuditUsageV2';
import {
    RiskAuditUsageV2FromJSON,
    RiskAuditUsageV2FromJSONTyped,
    RiskAuditUsageV2ToJSON,
    RiskAuditUsageV2ToJSONTyped,
} from './RiskAuditUsageV2';

/**
 * 
 * @export
 * @interface RiskAuditMetaV2
 */
export interface RiskAuditMetaV2 {
    /**
     * Analysis id
     */
    id: string;
    /**
     * Object type
     */
    object?: string;
    /**
     * Call duration (s)
     */
    callDurationS?: number;
    /**
     * ISO 8601 analyzed timestamp
     */
    analyzedAt?: string;
    /**
     * Usage block
     */
    usage: RiskAuditUsageV2;
    /**
     * Echoed client reference id
     */
    clientReferenceId?: string;
}

/**
 * Check if a given object implements the RiskAuditMetaV2 interface.
 */
export function instanceOfRiskAuditMetaV2(value: object): value is RiskAuditMetaV2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    return true;
}

export function RiskAuditMetaV2FromJSON(json: any): RiskAuditMetaV2 {
    return RiskAuditMetaV2FromJSONTyped(json, false);
}

export function RiskAuditMetaV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditMetaV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'] == null ? undefined : json['object'],
        'callDurationS': json['call_duration_s'] == null ? undefined : json['call_duration_s'],
        'analyzedAt': json['analyzed_at'] == null ? undefined : json['analyzed_at'],
        'usage': RiskAuditUsageV2FromJSON(json['usage']),
        'clientReferenceId': json['client_reference_id'] == null ? undefined : json['client_reference_id'],
    };
}

export function RiskAuditMetaV2ToJSON(json: any): RiskAuditMetaV2 {
    return RiskAuditMetaV2ToJSONTyped(json, false);
}

export function RiskAuditMetaV2ToJSONTyped(value?: RiskAuditMetaV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'call_duration_s': value['callDurationS'],
        'analyzed_at': value['analyzedAt'],
        'usage': RiskAuditUsageV2ToJSON(value['usage']),
        'client_reference_id': value['clientReferenceId'],
    };
}

