/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskAuditParticipantV2 } from './RiskAuditParticipantV2';
import {
    RiskAuditParticipantV2FromJSON,
    RiskAuditParticipantV2FromJSONTyped,
    RiskAuditParticipantV2ToJSON,
    RiskAuditParticipantV2ToJSONTyped,
} from './RiskAuditParticipantV2';

/**
 * 
 * @export
 * @interface RiskAuditParticipantsV2
 */
export interface RiskAuditParticipantsV2 {
    /**
     * Identified participants
     */
    identified?: Array<RiskAuditParticipantV2>;
    /**
     * inbound/outbound
     */
    callDirection?: string;
    /**
     * Role inference reliability
     */
    roleInferenceReliable?: boolean;
    /**
     * Identification status
     */
    identificationStatus?: string;
    /**
     * Unidentified items count
     */
    unidentifiedItemsCount?: number;
}

/**
 * Check if a given object implements the RiskAuditParticipantsV2 interface.
 */
export function instanceOfRiskAuditParticipantsV2(value: object): value is RiskAuditParticipantsV2 {
    return true;
}

export function RiskAuditParticipantsV2FromJSON(json: any): RiskAuditParticipantsV2 {
    return RiskAuditParticipantsV2FromJSONTyped(json, false);
}

export function RiskAuditParticipantsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditParticipantsV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'identified': json['identified'] == null ? undefined : ((json['identified'] as Array<any>).map(RiskAuditParticipantV2FromJSON)),
        'callDirection': json['call_direction'] == null ? undefined : json['call_direction'],
        'roleInferenceReliable': json['role_inference_reliable'] == null ? undefined : json['role_inference_reliable'],
        'identificationStatus': json['identification_status'] == null ? undefined : json['identification_status'],
        'unidentifiedItemsCount': json['unidentified_items_count'] == null ? undefined : json['unidentified_items_count'],
    };
}

export function RiskAuditParticipantsV2ToJSON(json: any): RiskAuditParticipantsV2 {
    return RiskAuditParticipantsV2ToJSONTyped(json, false);
}

export function RiskAuditParticipantsV2ToJSONTyped(value?: RiskAuditParticipantsV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identified': value['identified'] == null ? undefined : ((value['identified'] as Array<any>).map(RiskAuditParticipantV2ToJSON)),
        'call_direction': value['callDirection'],
        'role_inference_reliable': value['roleInferenceReliable'],
        'identification_status': value['identificationStatus'],
        'unidentified_items_count': value['unidentifiedItemsCount'],
    };
}

