/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskAuditConversationScoresV2 } from './RiskAuditConversationScoresV2';
import {
    RiskAuditConversationScoresV2FromJSON,
    RiskAuditConversationScoresV2FromJSONTyped,
    RiskAuditConversationScoresV2ToJSON,
    RiskAuditConversationScoresV2ToJSONTyped,
} from './RiskAuditConversationScoresV2';

/**
 * 
 * @export
 * @interface RiskAuditScoresV2
 */
export interface RiskAuditScoresV2 {
    /**
     * Conversation scores
     */
    conversation: RiskAuditConversationScoresV2;
    /**
     * Per-participant KPIs
     */
    perParticipant?: { [key: string]: any; };
}

/**
 * Check if a given object implements the RiskAuditScoresV2 interface.
 */
export function instanceOfRiskAuditScoresV2(value: object): value is RiskAuditScoresV2 {
    if (!('conversation' in value) || value['conversation'] === undefined) return false;
    return true;
}

export function RiskAuditScoresV2FromJSON(json: any): RiskAuditScoresV2 {
    return RiskAuditScoresV2FromJSONTyped(json, false);
}

export function RiskAuditScoresV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditScoresV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'conversation': RiskAuditConversationScoresV2FromJSON(json['conversation']),
        'perParticipant': json['per_participant'] == null ? undefined : json['per_participant'],
    };
}

export function RiskAuditScoresV2ToJSON(json: any): RiskAuditScoresV2 {
    return RiskAuditScoresV2ToJSONTyped(json, false);
}

export function RiskAuditScoresV2ToJSONTyped(value?: RiskAuditScoresV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation': RiskAuditConversationScoresV2ToJSON(value['conversation']),
        'per_participant': value['perParticipant'],
    };
}

