/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditScoringExplanationV2
 */
export interface RiskAuditScoringExplanationV2 {
    /**
     * Explanation summary
     */
    summary?: string;
    /**
     * Explanation steps
     */
    steps?: Array<any>;
}

/**
 * Check if a given object implements the RiskAuditScoringExplanationV2 interface.
 */
export function instanceOfRiskAuditScoringExplanationV2(value: object): value is RiskAuditScoringExplanationV2 {
    return true;
}

export function RiskAuditScoringExplanationV2FromJSON(json: any): RiskAuditScoringExplanationV2 {
    return RiskAuditScoringExplanationV2FromJSONTyped(json, false);
}

export function RiskAuditScoringExplanationV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditScoringExplanationV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'] == null ? undefined : json['summary'],
        'steps': json['steps'] == null ? undefined : json['steps'],
    };
}

export function RiskAuditScoringExplanationV2ToJSON(json: any): RiskAuditScoringExplanationV2 {
    return RiskAuditScoringExplanationV2ToJSONTyped(json, false);
}

export function RiskAuditScoringExplanationV2ToJSONTyped(value?: RiskAuditScoringExplanationV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
        'steps': value['steps'],
    };
}

