/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditAudioEventModelV2
 */
export interface RiskAuditAudioEventModelV2 {
    /**
     * MAC model text (i18n)
     */
    model?: string;
    /**
     * MAC description (i18n)
     */
    description?: string;
    /**
     * Temporal windows (s)
     */
    windowsS?: { [key: string]: any; };
}

/**
 * Check if a given object implements the RiskAuditAudioEventModelV2 interface.
 */
export function instanceOfRiskAuditAudioEventModelV2(value: object): value is RiskAuditAudioEventModelV2 {
    return true;
}

export function RiskAuditAudioEventModelV2FromJSON(json: any): RiskAuditAudioEventModelV2 {
    return RiskAuditAudioEventModelV2FromJSONTyped(json, false);
}

export function RiskAuditAudioEventModelV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditAudioEventModelV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'description': json['description'] == null ? undefined : json['description'],
        'windowsS': json['windows_s'] == null ? undefined : json['windows_s'],
    };
}

export function RiskAuditAudioEventModelV2ToJSON(json: any): RiskAuditAudioEventModelV2 {
    return RiskAuditAudioEventModelV2ToJSONTyped(json, false);
}

export function RiskAuditAudioEventModelV2ToJSONTyped(value?: RiskAuditAudioEventModelV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'description': value['description'],
        'windows_s': value['windowsS'],
    };
}

