/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskAuditDetectionItemV2 } from './RiskAuditDetectionItemV2';
import {
    RiskAuditDetectionItemV2FromJSON,
    RiskAuditDetectionItemV2FromJSONTyped,
    RiskAuditDetectionItemV2ToJSON,
    RiskAuditDetectionItemV2ToJSONTyped,
} from './RiskAuditDetectionItemV2';

/**
 * 
 * @export
 * @interface RiskAuditDetectionsV2
 */
export interface RiskAuditDetectionsV2 {
    /**
     * Active violations
     */
    violations?: Array<RiskAuditDetectionItemV2>;
    /**
     * Active positives
     */
    positives?: Array<RiskAuditDetectionItemV2>;
    /**
     * Client risk alerts
     */
    clientRiskAlerts?: Array<{ [key: string]: any; }>;
    /**
     * Client behavior alerts
     */
    clientBehaviorAlerts?: Array<{ [key: string]: any; }>;
    /**
     * Client negatives
     */
    clientNegatives?: Array<RiskAuditDetectionItemV2>;
}

/**
 * Check if a given object implements the RiskAuditDetectionsV2 interface.
 */
export function instanceOfRiskAuditDetectionsV2(value: object): value is RiskAuditDetectionsV2 {
    return true;
}

export function RiskAuditDetectionsV2FromJSON(json: any): RiskAuditDetectionsV2 {
    return RiskAuditDetectionsV2FromJSONTyped(json, false);
}

export function RiskAuditDetectionsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditDetectionsV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'violations': json['violations'] == null ? undefined : ((json['violations'] as Array<any>).map(RiskAuditDetectionItemV2FromJSON)),
        'positives': json['positives'] == null ? undefined : ((json['positives'] as Array<any>).map(RiskAuditDetectionItemV2FromJSON)),
        'clientRiskAlerts': json['client_risk_alerts'] == null ? undefined : json['client_risk_alerts'],
        'clientBehaviorAlerts': json['client_behavior_alerts'] == null ? undefined : json['client_behavior_alerts'],
        'clientNegatives': json['client_negatives'] == null ? undefined : ((json['client_negatives'] as Array<any>).map(RiskAuditDetectionItemV2FromJSON)),
    };
}

export function RiskAuditDetectionsV2ToJSON(json: any): RiskAuditDetectionsV2 {
    return RiskAuditDetectionsV2ToJSONTyped(json, false);
}

export function RiskAuditDetectionsV2ToJSONTyped(value?: RiskAuditDetectionsV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'violations': value['violations'] == null ? undefined : ((value['violations'] as Array<any>).map(RiskAuditDetectionItemV2ToJSON)),
        'positives': value['positives'] == null ? undefined : ((value['positives'] as Array<any>).map(RiskAuditDetectionItemV2ToJSON)),
        'client_risk_alerts': value['clientRiskAlerts'],
        'client_behavior_alerts': value['clientBehaviorAlerts'],
        'client_negatives': value['clientNegatives'] == null ? undefined : ((value['clientNegatives'] as Array<any>).map(RiskAuditDetectionItemV2ToJSON)),
    };
}

