/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskAuditParticipantsV2 } from './RiskAuditParticipantsV2';
import {
    RiskAuditParticipantsV2FromJSON,
    RiskAuditParticipantsV2FromJSONTyped,
    RiskAuditParticipantsV2ToJSON,
    RiskAuditParticipantsV2ToJSONTyped,
} from './RiskAuditParticipantsV2';
import type { RiskAuditAudioEventModelV2 } from './RiskAuditAudioEventModelV2';
import {
    RiskAuditAudioEventModelV2FromJSON,
    RiskAuditAudioEventModelV2FromJSONTyped,
    RiskAuditAudioEventModelV2ToJSON,
    RiskAuditAudioEventModelV2ToJSONTyped,
} from './RiskAuditAudioEventModelV2';
import type { RiskAuditScoresV2 } from './RiskAuditScoresV2';
import {
    RiskAuditScoresV2FromJSON,
    RiskAuditScoresV2FromJSONTyped,
    RiskAuditScoresV2ToJSON,
    RiskAuditScoresV2ToJSONTyped,
} from './RiskAuditScoresV2';
import type { RiskAuditDetectionsV2 } from './RiskAuditDetectionsV2';
import {
    RiskAuditDetectionsV2FromJSON,
    RiskAuditDetectionsV2FromJSONTyped,
    RiskAuditDetectionsV2ToJSON,
    RiskAuditDetectionsV2ToJSONTyped,
} from './RiskAuditDetectionsV2';
import type { RiskAuditIndexerV2 } from './RiskAuditIndexerV2';
import {
    RiskAuditIndexerV2FromJSON,
    RiskAuditIndexerV2FromJSONTyped,
    RiskAuditIndexerV2ToJSON,
    RiskAuditIndexerV2ToJSONTyped,
} from './RiskAuditIndexerV2';
import type { RiskAuditVerdictV2 } from './RiskAuditVerdictV2';
import {
    RiskAuditVerdictV2FromJSON,
    RiskAuditVerdictV2FromJSONTyped,
    RiskAuditVerdictV2ToJSON,
    RiskAuditVerdictV2ToJSONTyped,
} from './RiskAuditVerdictV2';
import type { RiskAuditAnalysisV2 } from './RiskAuditAnalysisV2';
import {
    RiskAuditAnalysisV2FromJSON,
    RiskAuditAnalysisV2FromJSONTyped,
    RiskAuditAnalysisV2ToJSON,
    RiskAuditAnalysisV2ToJSONTyped,
} from './RiskAuditAnalysisV2';
import type { RiskAuditScoringExplanationV2 } from './RiskAuditScoringExplanationV2';
import {
    RiskAuditScoringExplanationV2FromJSON,
    RiskAuditScoringExplanationV2FromJSONTyped,
    RiskAuditScoringExplanationV2ToJSON,
    RiskAuditScoringExplanationV2ToJSONTyped,
} from './RiskAuditScoringExplanationV2';
import type { RiskAuditAuditDecisionsV2 } from './RiskAuditAuditDecisionsV2';
import {
    RiskAuditAuditDecisionsV2FromJSON,
    RiskAuditAuditDecisionsV2FromJSONTyped,
    RiskAuditAuditDecisionsV2ToJSON,
    RiskAuditAuditDecisionsV2ToJSONTyped,
} from './RiskAuditAuditDecisionsV2';
import type { RiskAuditTimelineV2 } from './RiskAuditTimelineV2';
import {
    RiskAuditTimelineV2FromJSON,
    RiskAuditTimelineV2FromJSONTyped,
    RiskAuditTimelineV2ToJSON,
    RiskAuditTimelineV2ToJSONTyped,
} from './RiskAuditTimelineV2';
import type { RiskAuditSummaryV2 } from './RiskAuditSummaryV2';
import {
    RiskAuditSummaryV2FromJSON,
    RiskAuditSummaryV2FromJSONTyped,
    RiskAuditSummaryV2ToJSON,
    RiskAuditSummaryV2ToJSONTyped,
} from './RiskAuditSummaryV2';
import type { RiskAuditMetaV2 } from './RiskAuditMetaV2';
import {
    RiskAuditMetaV2FromJSON,
    RiskAuditMetaV2FromJSONTyped,
    RiskAuditMetaV2ToJSON,
    RiskAuditMetaV2ToJSONTyped,
} from './RiskAuditMetaV2';

/**
 * Response V2 (build_public_response_v2) — blocos logicos EN-US. Fonte: response_builder.py.
 * @export
 * @interface RiskAuditV2
 */
export interface RiskAuditV2 {
    /**
     * Identification + usage
     */
    meta: RiskAuditMetaV2;
    /**
     * Participants/roles/direction
     */
    participants: RiskAuditParticipantsV2;
    /**
     * Verdict + level + applied actions
     */
    verdict: RiskAuditVerdictV2;
    /**
     * Consolidated + per-participant scores
     */
    scores: RiskAuditScoresV2;
    /**
     * violations/positives/client alerts
     */
    detections: RiskAuditDetectionsV2;
    /**
     * global_metrics + final_analysis + frameworks
     */
    analysis: RiskAuditAnalysisV2;
    /**
     * turns_sentiment + audio_events + groups
     */
    timeline: RiskAuditTimelineV2;
    /**
     * MAC audio event semantics
     */
    audioEventModel: RiskAuditAudioEventModelV2;
    /**
     * Per-category summary (keyed by category)
     */
    categoriesSummary: { [key: string]: any; };
    /**
     * Suggested terms for bank
     */
    indexer: RiskAuditIndexerV2;
    /**
     * Executive summary counts
     */
    summary: RiskAuditSummaryV2;
    /**
     * Used actions i18n catalog (keyed by action)
     */
    actionsI18n: { [key: string]: any; };
    /**
     * Risk origin + validator changes
     */
    auditDecisions: RiskAuditAuditDecisionsV2;
    /**
     * Score composition explanation
     */
    scoringExplanation: RiskAuditScoringExplanationV2;
    /**
     * HTML report (base64 gzip)
     */
    htmlReport: string;
}

/**
 * Check if a given object implements the RiskAuditV2 interface.
 */
export function instanceOfRiskAuditV2(value: object): value is RiskAuditV2 {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    if (!('scores' in value) || value['scores'] === undefined) return false;
    if (!('detections' in value) || value['detections'] === undefined) return false;
    if (!('analysis' in value) || value['analysis'] === undefined) return false;
    if (!('timeline' in value) || value['timeline'] === undefined) return false;
    if ((!('audioEventModel' in (value as Record<string, any>)) && !('audio_event_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['audioEventModel'] === undefined && (value as Record<string, any>)['audio_event_model'] === undefined)) return false;
    if ((!('categoriesSummary' in (value as Record<string, any>)) && !('categories_summary' in (value as Record<string, any>))) || ((value as Record<string, any>)['categoriesSummary'] === undefined && (value as Record<string, any>)['categories_summary'] === undefined)) return false;
    if (!('indexer' in value) || value['indexer'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if ((!('actionsI18n' in (value as Record<string, any>)) && !('actions_i18n' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionsI18n'] === undefined && (value as Record<string, any>)['actions_i18n'] === undefined)) return false;
    if ((!('auditDecisions' in (value as Record<string, any>)) && !('audit_decisions' in (value as Record<string, any>))) || ((value as Record<string, any>)['auditDecisions'] === undefined && (value as Record<string, any>)['audit_decisions'] === undefined)) return false;
    if ((!('scoringExplanation' in (value as Record<string, any>)) && !('scoring_explanation' in (value as Record<string, any>))) || ((value as Record<string, any>)['scoringExplanation'] === undefined && (value as Record<string, any>)['scoring_explanation'] === undefined)) return false;
    if ((!('htmlReport' in (value as Record<string, any>)) && !('html_report' in (value as Record<string, any>))) || ((value as Record<string, any>)['htmlReport'] === undefined && (value as Record<string, any>)['html_report'] === undefined)) return false;
    return true;
}

export function RiskAuditV2FromJSON(json: any): RiskAuditV2 {
    return RiskAuditV2FromJSONTyped(json, false);
}

export function RiskAuditV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': RiskAuditMetaV2FromJSON(json['meta']),
        'participants': RiskAuditParticipantsV2FromJSON(json['participants']),
        'verdict': RiskAuditVerdictV2FromJSON(json['verdict']),
        'scores': RiskAuditScoresV2FromJSON(json['scores']),
        'detections': RiskAuditDetectionsV2FromJSON(json['detections']),
        'analysis': RiskAuditAnalysisV2FromJSON(json['analysis']),
        'timeline': RiskAuditTimelineV2FromJSON(json['timeline']),
        'audioEventModel': RiskAuditAudioEventModelV2FromJSON(json['audio_event_model']),
        'categoriesSummary': json['categories_summary'],
        'indexer': RiskAuditIndexerV2FromJSON(json['indexer']),
        'summary': RiskAuditSummaryV2FromJSON(json['summary']),
        'actionsI18n': json['actions_i18n'],
        'auditDecisions': RiskAuditAuditDecisionsV2FromJSON(json['audit_decisions']),
        'scoringExplanation': RiskAuditScoringExplanationV2FromJSON(json['scoring_explanation']),
        'htmlReport': json['html_report'],
    };
}

export function RiskAuditV2ToJSON(json: any): RiskAuditV2 {
    return RiskAuditV2ToJSONTyped(json, false);
}

export function RiskAuditV2ToJSONTyped(value?: RiskAuditV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': RiskAuditMetaV2ToJSON(value['meta']),
        'participants': RiskAuditParticipantsV2ToJSON(value['participants']),
        'verdict': RiskAuditVerdictV2ToJSON(value['verdict']),
        'scores': RiskAuditScoresV2ToJSON(value['scores']),
        'detections': RiskAuditDetectionsV2ToJSON(value['detections']),
        'analysis': RiskAuditAnalysisV2ToJSON(value['analysis']),
        'timeline': RiskAuditTimelineV2ToJSON(value['timeline']),
        'audio_event_model': RiskAuditAudioEventModelV2ToJSON(value['audioEventModel']),
        'categories_summary': value['categoriesSummary'],
        'indexer': RiskAuditIndexerV2ToJSON(value['indexer']),
        'summary': RiskAuditSummaryV2ToJSON(value['summary']),
        'actions_i18n': value['actionsI18n'],
        'audit_decisions': RiskAuditAuditDecisionsV2ToJSON(value['auditDecisions']),
        'scoring_explanation': RiskAuditScoringExplanationV2ToJSON(value['scoringExplanation']),
        'html_report': value['htmlReport'],
    };
}

