/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditDetectionItemV2
 */
export interface RiskAuditDetectionItemV2 {
    /**
     * Turn number
     */
    turn?: number;
    /**
     * Speaker
     */
    interlocutor?: string;
    /**
     * Role
     */
    role?: string;
    /**
     * Start (s)
     */
    timestampStartS?: number;
    /**
     * End (s)
     */
    timestampEndS?: number;
    /**
     * Formatted timestamp
     */
    timestampFormatted?: string;
    /**
     * Detected term
     */
    termText?: string;
    /**
     * Suggested term for bank
     */
    suggestedTermForBank?: any | null;
    /**
     * Category code
     */
    category?: string;
    /**
     * Category label (i18n)
     */
    categoryLabel: string;
    /**
     * Category color
     */
    categoryColor?: string;
    /**
     * Category icon
     */
    categoryIcon?: string;
    /**
     * Criticality
     */
    criticality?: string;
    /**
     * Category threshold
     */
    categoryThreshold?: number;
    /**
     * Category type
     */
    categoryType?: string;
    /**
     * Category group label (i18n)
     */
    categoryGroup: string;
    /**
     * Nature
     */
    nature?: string;
    /**
     * LLM confidence
     */
    llmConfidence?: number;
    /**
     * Reason
     */
    reason?: string;
    /**
     * Valid context
     */
    isValidContext?: boolean;
    /**
     * Risk probability
     */
    riskProbability?: number;
    /**
     * Risk impact
     */
    riskImpact?: number;
    /**
     * Category weight
     */
    categoryWeight?: number;
    /**
     * Turn sentiment
     */
    turnSentiment?: string;
    /**
     * Intensity
     */
    intensity?: any | null;
    /**
     * Total modifier applied
     */
    modApplied?: number;
    /**
     * Audio modifier applied
     */
    macApplied?: number;
    /**
     * Intensity modifier applied
     */
    mvadApplied?: number;
    /**
     * Modifier formula
     */
    modFormula?: string;
    /**
     * MAC details
     */
    macDetails?: Array<{ [key: string]: any; }>;
    /**
     * Calibration reason
     */
    calibrationReason?: string;
    /**
     * Final score
     */
    finalScore?: number;
    /**
     * Final score formula
     */
    finalScoreFormula?: string;
    /**
     * Conversation limit
     */
    conversationLimit?: any | null;
    /**
     * Apply saturation
     */
    applySaturation?: boolean;
    /**
     * Block repetition
     */
    blockRepetition?: boolean;
    /**
     * Status
     */
    status?: string;
    /**
     * Effective impact
     */
    effectiveImpact?: number;
    /**
     * Saturation factor
     */
    saturationFactor?: number;
    /**
     * Saturation formula
     */
    saturationFormula?: string;
    /**
     * Threshold formula
     */
    thresholdFormula?: string;
    /**
     * Blocked formula
     */
    blockedFormula?: string;
    /**
     * Reconciliation note
     */
    reconciliationNote?: string;
    /**
     * Violated frameworks
     */
    violatedFrameworks?: Array<any>;
    /**
     * Citation fidelity
     */
    citationFidelity?: boolean;
    /**
     * Subcategory code
     */
    subcategory?: string;
    /**
     * Subcategory label (i18n)
     */
    subcategoryLabel?: string;
}

/**
 * Check if a given object implements the RiskAuditDetectionItemV2 interface.
 */
export function instanceOfRiskAuditDetectionItemV2(value: object): value is RiskAuditDetectionItemV2 {
    if ((!('categoryLabel' in (value as Record<string, any>)) && !('category_label' in (value as Record<string, any>))) || ((value as Record<string, any>)['categoryLabel'] === undefined && (value as Record<string, any>)['category_label'] === undefined)) return false;
    if ((!('categoryGroup' in (value as Record<string, any>)) && !('category_group' in (value as Record<string, any>))) || ((value as Record<string, any>)['categoryGroup'] === undefined && (value as Record<string, any>)['category_group'] === undefined)) return false;
    return true;
}

export function RiskAuditDetectionItemV2FromJSON(json: any): RiskAuditDetectionItemV2 {
    return RiskAuditDetectionItemV2FromJSONTyped(json, false);
}

export function RiskAuditDetectionItemV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditDetectionItemV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'turn': json['turn'] == null ? undefined : json['turn'],
        'interlocutor': json['interlocutor'] == null ? undefined : json['interlocutor'],
        'role': json['role'] == null ? undefined : json['role'],
        'timestampStartS': json['timestamp_start_s'] == null ? undefined : json['timestamp_start_s'],
        'timestampEndS': json['timestamp_end_s'] == null ? undefined : json['timestamp_end_s'],
        'timestampFormatted': json['timestamp_formatted'] == null ? undefined : json['timestamp_formatted'],
        'termText': json['term_text'] == null ? undefined : json['term_text'],
        'suggestedTermForBank': json['suggested_term_for_bank'] === undefined ? undefined : json['suggested_term_for_bank'] === null ? null : json['suggested_term_for_bank'],
        'category': json['category'] == null ? undefined : json['category'],
        'categoryLabel': json['category_label'],
        'categoryColor': json['category_color'] == null ? undefined : json['category_color'],
        'categoryIcon': json['category_icon'] == null ? undefined : json['category_icon'],
        'criticality': json['criticality'] == null ? undefined : json['criticality'],
        'categoryThreshold': json['category_threshold'] == null ? undefined : json['category_threshold'],
        'categoryType': json['category_type'] == null ? undefined : json['category_type'],
        'categoryGroup': json['category_group'],
        'nature': json['nature'] == null ? undefined : json['nature'],
        'llmConfidence': json['llm_confidence'] == null ? undefined : json['llm_confidence'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'isValidContext': json['is_valid_context'] == null ? undefined : json['is_valid_context'],
        'riskProbability': json['risk_probability'] == null ? undefined : json['risk_probability'],
        'riskImpact': json['risk_impact'] == null ? undefined : json['risk_impact'],
        'categoryWeight': json['category_weight'] == null ? undefined : json['category_weight'],
        'turnSentiment': json['turn_sentiment'] == null ? undefined : json['turn_sentiment'],
        'intensity': json['intensity'] === undefined ? undefined : json['intensity'] === null ? null : json['intensity'],
        'modApplied': json['mod_applied'] == null ? undefined : json['mod_applied'],
        'macApplied': json['mac_applied'] == null ? undefined : json['mac_applied'],
        'mvadApplied': json['mvad_applied'] == null ? undefined : json['mvad_applied'],
        'modFormula': json['mod_formula'] == null ? undefined : json['mod_formula'],
        'macDetails': json['mac_details'] == null ? undefined : json['mac_details'],
        'calibrationReason': json['calibration_reason'] == null ? undefined : json['calibration_reason'],
        'finalScore': json['final_score'] == null ? undefined : json['final_score'],
        'finalScoreFormula': json['final_score_formula'] == null ? undefined : json['final_score_formula'],
        'conversationLimit': json['conversation_limit'] === undefined ? undefined : json['conversation_limit'] === null ? null : json['conversation_limit'],
        'applySaturation': json['apply_saturation'] == null ? undefined : json['apply_saturation'],
        'blockRepetition': json['block_repetition'] == null ? undefined : json['block_repetition'],
        'status': json['status'] == null ? undefined : json['status'],
        'effectiveImpact': json['effective_impact'] == null ? undefined : json['effective_impact'],
        'saturationFactor': json['saturation_factor'] == null ? undefined : json['saturation_factor'],
        'saturationFormula': json['saturation_formula'] == null ? undefined : json['saturation_formula'],
        'thresholdFormula': json['threshold_formula'] == null ? undefined : json['threshold_formula'],
        'blockedFormula': json['blocked_formula'] == null ? undefined : json['blocked_formula'],
        'reconciliationNote': json['reconciliation_note'] == null ? undefined : json['reconciliation_note'],
        'violatedFrameworks': json['violated_frameworks'] == null ? undefined : json['violated_frameworks'],
        'citationFidelity': json['citation_fidelity'] == null ? undefined : json['citation_fidelity'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'subcategoryLabel': json['subcategory_label'] == null ? undefined : json['subcategory_label'],
    };
}

export function RiskAuditDetectionItemV2ToJSON(json: any): RiskAuditDetectionItemV2 {
    return RiskAuditDetectionItemV2ToJSONTyped(json, false);
}

export function RiskAuditDetectionItemV2ToJSONTyped(value?: RiskAuditDetectionItemV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'turn': value['turn'],
        'interlocutor': value['interlocutor'],
        'role': value['role'],
        'timestamp_start_s': value['timestampStartS'],
        'timestamp_end_s': value['timestampEndS'],
        'timestamp_formatted': value['timestampFormatted'],
        'term_text': value['termText'],
        'suggested_term_for_bank': value['suggestedTermForBank'],
        'category': value['category'],
        'category_label': value['categoryLabel'],
        'category_color': value['categoryColor'],
        'category_icon': value['categoryIcon'],
        'criticality': value['criticality'],
        'category_threshold': value['categoryThreshold'],
        'category_type': value['categoryType'],
        'category_group': value['categoryGroup'],
        'nature': value['nature'],
        'llm_confidence': value['llmConfidence'],
        'reason': value['reason'],
        'is_valid_context': value['isValidContext'],
        'risk_probability': value['riskProbability'],
        'risk_impact': value['riskImpact'],
        'category_weight': value['categoryWeight'],
        'turn_sentiment': value['turnSentiment'],
        'intensity': value['intensity'],
        'mod_applied': value['modApplied'],
        'mac_applied': value['macApplied'],
        'mvad_applied': value['mvadApplied'],
        'mod_formula': value['modFormula'],
        'mac_details': value['macDetails'],
        'calibration_reason': value['calibrationReason'],
        'final_score': value['finalScore'],
        'final_score_formula': value['finalScoreFormula'],
        'conversation_limit': value['conversationLimit'],
        'apply_saturation': value['applySaturation'],
        'block_repetition': value['blockRepetition'],
        'status': value['status'],
        'effective_impact': value['effectiveImpact'],
        'saturation_factor': value['saturationFactor'],
        'saturation_formula': value['saturationFormula'],
        'threshold_formula': value['thresholdFormula'],
        'blocked_formula': value['blockedFormula'],
        'reconciliation_note': value['reconciliationNote'],
        'violated_frameworks': value['violatedFrameworks'],
        'citation_fidelity': value['citationFidelity'],
        'subcategory': value['subcategory'],
        'subcategory_label': value['subcategoryLabel'],
    };
}

