/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskAuditAppliedActionV2 } from './RiskAuditAppliedActionV2';
import {
    RiskAuditAppliedActionV2FromJSON,
    RiskAuditAppliedActionV2FromJSONTyped,
    RiskAuditAppliedActionV2ToJSON,
    RiskAuditAppliedActionV2ToJSONTyped,
} from './RiskAuditAppliedActionV2';

/**
 * 
 * @export
 * @interface RiskAuditVerdictV2
 */
export interface RiskAuditVerdictV2 {
    /**
     * Human-readable verdict
     */
    label?: string;
    /**
     * Classification level code
     */
    levelCode?: string;
    /**
     * Level color
     */
    color?: string;
    /**
     * Level icon
     */
    icon?: string;
    /**
     * Risk matrix
     */
    riskMatrix?: { [key: string]: any; };
    /**
     * Applied actions
     */
    appliedActions?: Array<RiskAuditAppliedActionV2>;
    /**
     * Decision details
     */
    decisionDetails?: any | null;
}

/**
 * Check if a given object implements the RiskAuditVerdictV2 interface.
 */
export function instanceOfRiskAuditVerdictV2(value: object): value is RiskAuditVerdictV2 {
    return true;
}

export function RiskAuditVerdictV2FromJSON(json: any): RiskAuditVerdictV2 {
    return RiskAuditVerdictV2FromJSONTyped(json, false);
}

export function RiskAuditVerdictV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditVerdictV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'levelCode': json['level_code'] == null ? undefined : json['level_code'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'riskMatrix': json['risk_matrix'] == null ? undefined : json['risk_matrix'],
        'appliedActions': json['applied_actions'] == null ? undefined : ((json['applied_actions'] as Array<any>).map(RiskAuditAppliedActionV2FromJSON)),
        'decisionDetails': json['decision_details'] === undefined ? undefined : json['decision_details'] === null ? null : json['decision_details'],
    };
}

export function RiskAuditVerdictV2ToJSON(json: any): RiskAuditVerdictV2 {
    return RiskAuditVerdictV2ToJSONTyped(json, false);
}

export function RiskAuditVerdictV2ToJSONTyped(value?: RiskAuditVerdictV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'level_code': value['levelCode'],
        'color': value['color'],
        'icon': value['icon'],
        'risk_matrix': value['riskMatrix'],
        'applied_actions': value['appliedActions'] == null ? undefined : ((value['appliedActions'] as Array<any>).map(RiskAuditAppliedActionV2ToJSON)),
        'decision_details': value['decisionDetails'],
    };
}

