/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditTimelineV2
 */
export interface RiskAuditTimelineV2 {
    /**
     * Per-turn sentiment
     */
    turnsSentiment?: Array<{ [key: string]: any; }>;
    /**
     * Audio events (i18n)
     */
    audioEvents?: Array<{ [key: string]: any; }>;
    /**
     * Audio groups found
     */
    audioGroupsFound?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the RiskAuditTimelineV2 interface.
 */
export function instanceOfRiskAuditTimelineV2(value: object): value is RiskAuditTimelineV2 {
    return true;
}

export function RiskAuditTimelineV2FromJSON(json: any): RiskAuditTimelineV2 {
    return RiskAuditTimelineV2FromJSONTyped(json, false);
}

export function RiskAuditTimelineV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditTimelineV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'turnsSentiment': json['turns_sentiment'] == null ? undefined : json['turns_sentiment'],
        'audioEvents': json['audio_events'] == null ? undefined : json['audio_events'],
        'audioGroupsFound': json['audio_groups_found'] == null ? undefined : json['audio_groups_found'],
    };
}

export function RiskAuditTimelineV2ToJSON(json: any): RiskAuditTimelineV2 {
    return RiskAuditTimelineV2ToJSONTyped(json, false);
}

export function RiskAuditTimelineV2ToJSONTyped(value?: RiskAuditTimelineV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'turns_sentiment': value['turnsSentiment'],
        'audio_events': value['audioEvents'],
        'audio_groups_found': value['audioGroupsFound'],
    };
}

