/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiagnosticAudioEvent } from './DiagnosticAudioEvent';
import {
    DiagnosticAudioEventFromJSON,
    DiagnosticAudioEventFromJSONTyped,
    DiagnosticAudioEventToJSON,
    DiagnosticAudioEventToJSONTyped,
} from './DiagnosticAudioEvent';
import type { Participant } from './Participant';
import {
    ParticipantFromJSON,
    ParticipantFromJSONTyped,
    ParticipantToJSON,
    ParticipantToJSONTyped,
} from './Participant';

/**
 * 
 * @export
 * @interface RiskAuditRequest
 */
export interface RiskAuditRequest {
    /**
     * Analysis model. Always 'falaai-risk-audit-1'
     */
    model?: string;
    /**
     * Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters
     */
    text?: string;
    /**
     * Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters
     */
    dialog?: string;
    /**
     * Audio events with timestamps (correlated with turns when diarization is present)
     */
    audioEvents?: Array<DiagnosticAudioEvent>;
    /**
     * Total audio duration in seconds. Required. Max 3h (10800s).
     */
    durationSeconds: number;
    /**
     * Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES.
     */
    language: string;
    /**
     * Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from 'language'. Accepted: pt-BR, en-US, es-ES.
     */
    responseLanguage: string;
    /**
     * Who originated the call. inbound=client called, outbound=company called. If omitted, LLM infers from context.
     */
    callDirection?: RiskAuditRequestCallDirectionEnum;
    /**
     * Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth — no inference.
     */
    participants?: Array<Participant>;
    /**
     * Response format version. v1=legacy flat PT-BR, v2=structured EN-US blocks.
     */
    responseFormat?: string;
    /**
     * Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
     */
    clientReferenceId?: string;
}


/**
 * @export
 */
export const RiskAuditRequestCallDirectionEnum = {
    Inbound: 'inbound',
    Outbound: 'outbound',
} as const;
export type RiskAuditRequestCallDirectionEnum = typeof RiskAuditRequestCallDirectionEnum[keyof typeof RiskAuditRequestCallDirectionEnum];


/**
 * Check if a given object implements the RiskAuditRequest interface.
 */
export function instanceOfRiskAuditRequest(value: object): value is RiskAuditRequest {
    if ((!('durationSeconds' in (value as Record<string, any>)) && !('duration_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['durationSeconds'] === undefined && (value as Record<string, any>)['duration_seconds'] === undefined)) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if ((!('responseLanguage' in (value as Record<string, any>)) && !('response_language' in (value as Record<string, any>))) || ((value as Record<string, any>)['responseLanguage'] === undefined && (value as Record<string, any>)['response_language'] === undefined)) return false;
    return true;
}

export function RiskAuditRequestFromJSON(json: any): RiskAuditRequest {
    return RiskAuditRequestFromJSONTyped(json, false);
}

export function RiskAuditRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'text': json['text'] == null ? undefined : json['text'],
        'dialog': json['dialog'] == null ? undefined : json['dialog'],
        'audioEvents': json['audio_events'] == null ? undefined : ((json['audio_events'] as Array<any>).map(DiagnosticAudioEventFromJSON)),
        'durationSeconds': json['duration_seconds'],
        'language': json['language'],
        'responseLanguage': json['response_language'],
        'callDirection': json['call_direction'] == null ? undefined : json['call_direction'],
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(ParticipantFromJSON)),
        'responseFormat': json['response_format'] == null ? undefined : json['response_format'],
        'clientReferenceId': json['client_reference_id'] == null ? undefined : json['client_reference_id'],
    };
}

export function RiskAuditRequestToJSON(json: any): RiskAuditRequest {
    return RiskAuditRequestToJSONTyped(json, false);
}

export function RiskAuditRequestToJSONTyped(value?: RiskAuditRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'text': value['text'],
        'dialog': value['dialog'],
        'audio_events': value['audioEvents'] == null ? undefined : ((value['audioEvents'] as Array<any>).map(DiagnosticAudioEventToJSON)),
        'duration_seconds': value['durationSeconds'],
        'language': value['language'],
        'response_language': value['responseLanguage'],
        'call_direction': value['callDirection'],
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(ParticipantToJSON)),
        'response_format': value['responseFormat'],
        'client_reference_id': value['clientReferenceId'],
    };
}

