/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditConversationScoresV2
 */
export interface RiskAuditConversationScoresV2 {
    /**
     * Consolidated score
     */
    consolidatedScore?: number;
    /**
     * Violation density/min
     */
    violationDensityPerMin?: number;
    /**
     * Sentiment trend
     */
    sentimentTrend?: any | null;
    /**
     * % turns with violation
     */
    pctTurnsWithViolation?: number;
    /**
     * Most critical turn
     */
    mostCriticalTurn?: any | null;
    /**
     * Positive:negative ratio
     */
    positiveNegativeRatio?: any | null;
    /**
     * Global risk severity code
     */
    globalRiskSeverity?: string;
    /**
     * Global risk severity label
     */
    globalRiskSeverityLabel?: string;
    /**
     * Global risk severity color
     */
    globalRiskSeverityColor?: string;
    /**
     * Risk likelihood avg
     */
    riskLikelihoodAvg?: number;
    /**
     * Risk impact avg
     */
    riskImpactAvg?: number;
}

/**
 * Check if a given object implements the RiskAuditConversationScoresV2 interface.
 */
export function instanceOfRiskAuditConversationScoresV2(value: object): value is RiskAuditConversationScoresV2 {
    return true;
}

export function RiskAuditConversationScoresV2FromJSON(json: any): RiskAuditConversationScoresV2 {
    return RiskAuditConversationScoresV2FromJSONTyped(json, false);
}

export function RiskAuditConversationScoresV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditConversationScoresV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'consolidatedScore': json['consolidated_score'] == null ? undefined : json['consolidated_score'],
        'violationDensityPerMin': json['violation_density_per_min'] == null ? undefined : json['violation_density_per_min'],
        'sentimentTrend': json['sentiment_trend'] === undefined ? undefined : json['sentiment_trend'] === null ? null : json['sentiment_trend'],
        'pctTurnsWithViolation': json['pct_turns_with_violation'] == null ? undefined : json['pct_turns_with_violation'],
        'mostCriticalTurn': json['most_critical_turn'] === undefined ? undefined : json['most_critical_turn'] === null ? null : json['most_critical_turn'],
        'positiveNegativeRatio': json['positive_negative_ratio'] === undefined ? undefined : json['positive_negative_ratio'] === null ? null : json['positive_negative_ratio'],
        'globalRiskSeverity': json['global_risk_severity'] == null ? undefined : json['global_risk_severity'],
        'globalRiskSeverityLabel': json['global_risk_severity_label'] == null ? undefined : json['global_risk_severity_label'],
        'globalRiskSeverityColor': json['global_risk_severity_color'] == null ? undefined : json['global_risk_severity_color'],
        'riskLikelihoodAvg': json['risk_likelihood_avg'] == null ? undefined : json['risk_likelihood_avg'],
        'riskImpactAvg': json['risk_impact_avg'] == null ? undefined : json['risk_impact_avg'],
    };
}

export function RiskAuditConversationScoresV2ToJSON(json: any): RiskAuditConversationScoresV2 {
    return RiskAuditConversationScoresV2ToJSONTyped(json, false);
}

export function RiskAuditConversationScoresV2ToJSONTyped(value?: RiskAuditConversationScoresV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consolidated_score': value['consolidatedScore'],
        'violation_density_per_min': value['violationDensityPerMin'],
        'sentiment_trend': value['sentimentTrend'],
        'pct_turns_with_violation': value['pctTurnsWithViolation'],
        'most_critical_turn': value['mostCriticalTurn'],
        'positive_negative_ratio': value['positiveNegativeRatio'],
        'global_risk_severity': value['globalRiskSeverity'],
        'global_risk_severity_label': value['globalRiskSeverityLabel'],
        'global_risk_severity_color': value['globalRiskSeverityColor'],
        'risk_likelihood_avg': value['riskLikelihoodAvg'],
        'risk_impact_avg': value['riskImpactAvg'],
    };
}

