/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditAppliedActionV2
 */
export interface RiskAuditAppliedActionV2 {
    /**
     * Action type code
     */
    actionType: string;
    /**
     * Action label
     */
    label: string;
    /**
     * Action description
     */
    description: string;
    /**
     * CRITICO/ALTO/MEDIO/BAIXO
     */
    priority: string;
    /**
     * Color
     */
    color?: string;
    /**
     * Icon
     */
    icon?: string;
    /**
     * Condition
     */
    condition?: string;
    /**
     * Reason
     */
    reason?: string;
}

/**
 * Check if a given object implements the RiskAuditAppliedActionV2 interface.
 */
export function instanceOfRiskAuditAppliedActionV2(value: object): value is RiskAuditAppliedActionV2 {
    if ((!('actionType' in (value as Record<string, any>)) && !('action_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionType'] === undefined && (value as Record<string, any>)['action_type'] === undefined)) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function RiskAuditAppliedActionV2FromJSON(json: any): RiskAuditAppliedActionV2 {
    return RiskAuditAppliedActionV2FromJSONTyped(json, false);
}

export function RiskAuditAppliedActionV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditAppliedActionV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'actionType': json['action_type'],
        'label': json['label'],
        'description': json['description'],
        'priority': json['priority'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'condition': json['condition'] == null ? undefined : json['condition'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function RiskAuditAppliedActionV2ToJSON(json: any): RiskAuditAppliedActionV2 {
    return RiskAuditAppliedActionV2ToJSONTyped(json, false);
}

export function RiskAuditAppliedActionV2ToJSONTyped(value?: RiskAuditAppliedActionV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action_type': value['actionType'],
        'label': value['label'],
        'description': value['description'],
        'priority': value['priority'],
        'color': value['color'],
        'icon': value['icon'],
        'condition': value['condition'],
        'reason': value['reason'],
    };
}

