/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskAuditUsageV2
 */
export interface RiskAuditUsageV2 {
    /**
     * Characters analyzed
     */
    characters: number;
    /**
     * Credits consumed
     */
    creditsConsumed: number;
    /**
     * Processing time (ms)
     */
    processingMs: number;
}

/**
 * Check if a given object implements the RiskAuditUsageV2 interface.
 */
export function instanceOfRiskAuditUsageV2(value: object): value is RiskAuditUsageV2 {
    if (!('characters' in value) || value['characters'] === undefined) return false;
    if ((!('creditsConsumed' in (value as Record<string, any>)) && !('credits_consumed' in (value as Record<string, any>))) || ((value as Record<string, any>)['creditsConsumed'] === undefined && (value as Record<string, any>)['credits_consumed'] === undefined)) return false;
    if ((!('processingMs' in (value as Record<string, any>)) && !('processing_ms' in (value as Record<string, any>))) || ((value as Record<string, any>)['processingMs'] === undefined && (value as Record<string, any>)['processing_ms'] === undefined)) return false;
    return true;
}

export function RiskAuditUsageV2FromJSON(json: any): RiskAuditUsageV2 {
    return RiskAuditUsageV2FromJSONTyped(json, false);
}

export function RiskAuditUsageV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskAuditUsageV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'characters': json['characters'],
        'creditsConsumed': json['credits_consumed'],
        'processingMs': json['processing_ms'],
    };
}

export function RiskAuditUsageV2ToJSON(json: any): RiskAuditUsageV2 {
    return RiskAuditUsageV2ToJSONTyped(json, false);
}

export function RiskAuditUsageV2ToJSONTyped(value?: RiskAuditUsageV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'characters': value['characters'],
        'credits_consumed': value['creditsConsumed'],
        'processing_ms': value['processingMs'],
    };
}

