/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioInputMeta } from './AudioInputMeta';
import {
    AudioInputMetaFromJSON,
    AudioInputMetaFromJSONTyped,
    AudioInputMetaToJSON,
    AudioInputMetaToJSONTyped,
} from './AudioInputMeta';
import type { AudioEvent } from './AudioEvent';
import {
    AudioEventFromJSON,
    AudioEventFromJSONTyped,
    AudioEventToJSON,
    AudioEventToJSONTyped,
} from './AudioEvent';
import type { TranscriptionUsage } from './TranscriptionUsage';
import {
    TranscriptionUsageFromJSON,
    TranscriptionUsageFromJSONTyped,
    TranscriptionUsageToJSON,
    TranscriptionUsageToJSONTyped,
} from './TranscriptionUsage';

/**
 * 
 * @export
 * @interface TranscriptionResponse
 */
export interface TranscriptionResponse {
    /**
     * Unique transcription identifier. Prefix 'tr-' followed by UUID
     */
    id: string;
    /**
     * Returned object type. Always 'transcription'
     */
    object: string;
    /**
     * Model used for transcription. Ex: 'falaai-transcribe-1'
     */
    model: string;
    /**
     * Original audio file name uploaded
     */
    filename: string;
    /**
     * Processing datetime in ISO 8601 UTC format
     */
    processedAt: string;
    /**
     * Usage and processing information
     */
    usage: TranscriptionUsage;
    /**
     * ISO 639-3 language code detected in audio. Ex: 'por' (Portuguese), 'eng' (English), 'spa' (Spanish)
     */
    language: string;
    /**
     * Language detection confidence level (0.0 to 1.0). Higher is more reliable
     */
    languageConfidence?: number;
    /**
     * Total audio duration in seconds
     */
    durationSeconds: number;
    /**
     * Full transcription as plain text, including audio events in brackets
     */
    text: string;
    /**
     * Turn-by-turn formatted transcript with speaker identification and start/end timestamps
     */
    dialog: string;
    /**
     * List of detected audio events (laughs, sighs, pauses, etc) with timestamps and duration
     */
    audioEvents: Array<AudioEvent>;
    /**
     * Unique audio event types found in transcription, alphabetically sorted
     */
    eventTypes: Array<string>;
    /**
     * Total number of recognized words in transcription
     */
    wordCount: number;
    /**
     * Metadados do arquivo de audio enviado (duracao, formato, codec, sample rate, canais)
     */
    input: AudioInputMeta;
    /**
     * Client-supplied ID echoed verbatim (if provided in request)
     */
    clientReferenceId?: string;
}

/**
 * Check if a given object implements the TranscriptionResponse interface.
 */
export function instanceOfTranscriptionResponse(value: object): value is TranscriptionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if ((!('processedAt' in (value as Record<string, any>)) && !('processed_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['processedAt'] === undefined && (value as Record<string, any>)['processed_at'] === undefined)) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if ((!('durationSeconds' in (value as Record<string, any>)) && !('duration_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['durationSeconds'] === undefined && (value as Record<string, any>)['duration_seconds'] === undefined)) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('dialog' in value) || value['dialog'] === undefined) return false;
    if ((!('audioEvents' in (value as Record<string, any>)) && !('audio_events' in (value as Record<string, any>))) || ((value as Record<string, any>)['audioEvents'] === undefined && (value as Record<string, any>)['audio_events'] === undefined)) return false;
    if ((!('eventTypes' in (value as Record<string, any>)) && !('event_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['eventTypes'] === undefined && (value as Record<string, any>)['event_types'] === undefined)) return false;
    if ((!('wordCount' in (value as Record<string, any>)) && !('word_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['wordCount'] === undefined && (value as Record<string, any>)['word_count'] === undefined)) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function TranscriptionResponseFromJSON(json: any): TranscriptionResponse {
    return TranscriptionResponseFromJSONTyped(json, false);
}

export function TranscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'model': json['model'],
        'filename': json['filename'],
        'processedAt': json['processed_at'],
        'usage': TranscriptionUsageFromJSON(json['usage']),
        'language': json['language'],
        'languageConfidence': json['language_confidence'] == null ? undefined : json['language_confidence'],
        'durationSeconds': json['duration_seconds'],
        'text': json['text'],
        'dialog': json['dialog'],
        'audioEvents': ((json['audio_events'] as Array<any>).map(AudioEventFromJSON)),
        'eventTypes': json['event_types'],
        'wordCount': json['word_count'],
        'input': AudioInputMetaFromJSON(json['input']),
        'clientReferenceId': json['client_reference_id'] == null ? undefined : json['client_reference_id'],
    };
}

export function TranscriptionResponseToJSON(json: any): TranscriptionResponse {
    return TranscriptionResponseToJSONTyped(json, false);
}

export function TranscriptionResponseToJSONTyped(value?: TranscriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'model': value['model'],
        'filename': value['filename'],
        'processed_at': value['processedAt'],
        'usage': TranscriptionUsageToJSON(value['usage']),
        'language': value['language'],
        'language_confidence': value['languageConfidence'],
        'duration_seconds': value['durationSeconds'],
        'text': value['text'],
        'dialog': value['dialog'],
        'audio_events': ((value['audioEvents'] as Array<any>).map(AudioEventToJSON)),
        'event_types': value['eventTypes'],
        'word_count': value['wordCount'],
        'input': AudioInputMetaToJSON(value['input']),
        'client_reference_id': value['clientReferenceId'],
    };
}

