/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranscriptionUsage
 */
export interface TranscriptionUsage {
    /**
     * Actual audio duration processed in seconds
     */
    audioSeconds: number;
    /**
     * Number of credits consumed in this request
     */
    creditsConsumed: number;
    /**
     * Total processing time in milliseconds
     */
    processingMs: number;
}

/**
 * Check if a given object implements the TranscriptionUsage interface.
 */
export function instanceOfTranscriptionUsage(value: object): value is TranscriptionUsage {
    if ((!('audioSeconds' in (value as Record<string, any>)) && !('audio_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['audioSeconds'] === undefined && (value as Record<string, any>)['audio_seconds'] === undefined)) return false;
    if ((!('creditsConsumed' in (value as Record<string, any>)) && !('credits_consumed' in (value as Record<string, any>))) || ((value as Record<string, any>)['creditsConsumed'] === undefined && (value as Record<string, any>)['credits_consumed'] === undefined)) return false;
    if ((!('processingMs' in (value as Record<string, any>)) && !('processing_ms' in (value as Record<string, any>))) || ((value as Record<string, any>)['processingMs'] === undefined && (value as Record<string, any>)['processing_ms'] === undefined)) return false;
    return true;
}

export function TranscriptionUsageFromJSON(json: any): TranscriptionUsage {
    return TranscriptionUsageFromJSONTyped(json, false);
}

export function TranscriptionUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscriptionUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'audioSeconds': json['audio_seconds'],
        'creditsConsumed': json['credits_consumed'],
        'processingMs': json['processing_ms'],
    };
}

export function TranscriptionUsageToJSON(json: any): TranscriptionUsage {
    return TranscriptionUsageToJSONTyped(json, false);
}

export function TranscriptionUsageToJSONTyped(value?: TranscriptionUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audio_seconds': value['audioSeconds'],
        'credits_consumed': value['creditsConsumed'],
        'processing_ms': value['processingMs'],
    };
}

