/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailEvent } from './EmailEvent';
import {
    EmailEventFromJSON,
    EmailEventFromJSONTyped,
    EmailEventToJSON,
    EmailEventToJSONTyped,
} from './EmailEvent';

/**
 * 
 * @export
 * @interface UpdateEmailAlertRequest
 */
export interface UpdateEmailAlertRequest {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    email?: string;
    /**
     * 
     */
    events?: Array<EmailEvent>;
    /**
     * 
     */
    active?: boolean;
}

/**
 * Check if a given object implements the UpdateEmailAlertRequest interface.
 */
export function instanceOfUpdateEmailAlertRequest(value: object): value is UpdateEmailAlertRequest {
    return true;
}

export function UpdateEmailAlertRequestFromJSON(json: any): UpdateEmailAlertRequest {
    return UpdateEmailAlertRequestFromJSONTyped(json, false);
}

export function UpdateEmailAlertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailAlertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(EmailEventFromJSON)),
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function UpdateEmailAlertRequestToJSON(json: any): UpdateEmailAlertRequest {
    return UpdateEmailAlertRequestToJSONTyped(json, false);
}

export function UpdateEmailAlertRequestToJSONTyped(value?: UpdateEmailAlertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(EmailEventToJSON)),
        'active': value['active'],
    };
}

