/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEvent } from './WebhookEvent';
import {
    WebhookEventFromJSON,
    WebhookEventFromJSONTyped,
    WebhookEventToJSON,
    WebhookEventToJSONTyped,
} from './WebhookEvent';

/**
 * 
 * @export
 * @interface UpdateWebhookRequest
 */
export interface UpdateWebhookRequest {
    /**
     * Nome identificador
     */
    name?: string;
    /**
     * URL HTTPS destino
     */
    url?: string;
    /**
     * Eventos subscritos
     */
    events?: Array<WebhookEvent>;
    /**
     * Habilita retry exponencial
     */
    retryEnabled?: boolean;
    /**
     * Ativa/desativa sem deletar
     */
    active?: boolean;
}

/**
 * Check if a given object implements the UpdateWebhookRequest interface.
 */
export function instanceOfUpdateWebhookRequest(value: object): value is UpdateWebhookRequest {
    return true;
}

export function UpdateWebhookRequestFromJSON(json: any): UpdateWebhookRequest {
    return UpdateWebhookRequestFromJSONTyped(json, false);
}

export function UpdateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(WebhookEventFromJSON)),
        'retryEnabled': json['retry_enabled'] == null ? undefined : json['retry_enabled'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function UpdateWebhookRequestToJSON(json: any): UpdateWebhookRequest {
    return UpdateWebhookRequestToJSONTyped(json, false);
}

export function UpdateWebhookRequestToJSONTyped(value?: UpdateWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(WebhookEventToJSON)),
        'retry_enabled': value['retryEnabled'],
        'active': value['active'],
    };
}

