/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageByKeyItem
 */
export interface UsageByKeyItem {
    /**
     * API key id
     */
    keyId: string;
    /**
     * API key name
     */
    keyName: string;
    /**
     * Total credits consumed by the key
     */
    totalCredits: number;
    /**
     * Number of requests
     */
    requestCount: number;
    /**
     * ISO 8601 of last use (null if never)
     */
    lastUsed?: string;
}

/**
 * Check if a given object implements the UsageByKeyItem interface.
 */
export function instanceOfUsageByKeyItem(value: object): value is UsageByKeyItem {
    if ((!('keyId' in (value as Record<string, any>)) && !('key_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['keyId'] === undefined && (value as Record<string, any>)['key_id'] === undefined)) return false;
    if ((!('keyName' in (value as Record<string, any>)) && !('key_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['keyName'] === undefined && (value as Record<string, any>)['key_name'] === undefined)) return false;
    if ((!('totalCredits' in (value as Record<string, any>)) && !('total_credits' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalCredits'] === undefined && (value as Record<string, any>)['total_credits'] === undefined)) return false;
    if ((!('requestCount' in (value as Record<string, any>)) && !('request_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestCount'] === undefined && (value as Record<string, any>)['request_count'] === undefined)) return false;
    return true;
}

export function UsageByKeyItemFromJSON(json: any): UsageByKeyItem {
    return UsageByKeyItemFromJSONTyped(json, false);
}

export function UsageByKeyItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageByKeyItem {
    if (json == null) {
        return json;
    }
    return {
        
        'keyId': json['key_id'],
        'keyName': json['key_name'],
        'totalCredits': json['total_credits'],
        'requestCount': json['request_count'],
        'lastUsed': json['last_used'] == null ? undefined : json['last_used'],
    };
}

export function UsageByKeyItemToJSON(json: any): UsageByKeyItem {
    return UsageByKeyItemToJSONTyped(json, false);
}

export function UsageByKeyItemToJSONTyped(value?: UsageByKeyItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_id': value['keyId'],
        'key_name': value['keyName'],
        'total_credits': value['totalCredits'],
        'request_count': value['requestCount'],
        'last_used': value['lastUsed'],
    };
}

