/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsageLogItem } from './UsageLogItem';
import {
    UsageLogItemFromJSON,
    UsageLogItemFromJSONTyped,
    UsageLogItemToJSON,
    UsageLogItemToJSONTyped,
} from './UsageLogItem';

/**
 * 
 * @export
 * @interface UsageLogResponse
 */
export interface UsageLogResponse {
    /**
     * 
     */
    data: Array<UsageLogItem>;
    /**
     * 
     */
    page: number;
    /**
     * 
     */
    limit: number;
}

/**
 * Check if a given object implements the UsageLogResponse interface.
 */
export function instanceOfUsageLogResponse(value: object): value is UsageLogResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function UsageLogResponseFromJSON(json: any): UsageLogResponse {
    return UsageLogResponseFromJSONTyped(json, false);
}

export function UsageLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageLogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UsageLogItemFromJSON)),
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function UsageLogResponseToJSON(json: any): UsageLogResponse {
    return UsageLogResponseToJSONTyped(json, false);
}

export function UsageLogResponseToJSONTyped(value?: UsageLogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UsageLogItemToJSON)),
        'page': value['page'],
        'limit': value['limit'],
    };
}

