/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageLogItem
 */
export interface UsageLogItem {
    /**
     * Usage log entry id
     */
    id: string;
    /**
     * Endpoint called
     */
    endpoint: string;
    /**
     * Credits consumed
     */
    creditsCost: number;
    /**
     * Result status
     */
    status: string;
    /**
     * Errors count
     */
    errorsCount: number;
    /**
     * ISO 8601 timestamp
     */
    createdAt: string;
}

/**
 * Check if a given object implements the UsageLogItem interface.
 */
export function instanceOfUsageLogItem(value: object): value is UsageLogItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if ((!('creditsCost' in (value as Record<string, any>)) && !('credits_cost' in (value as Record<string, any>))) || ((value as Record<string, any>)['creditsCost'] === undefined && (value as Record<string, any>)['credits_cost'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('errorsCount' in (value as Record<string, any>)) && !('errors_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['errorsCount'] === undefined && (value as Record<string, any>)['errors_count'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function UsageLogItemFromJSON(json: any): UsageLogItem {
    return UsageLogItemFromJSONTyped(json, false);
}

export function UsageLogItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageLogItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'endpoint': json['endpoint'],
        'creditsCost': json['credits_cost'],
        'status': json['status'],
        'errorsCount': json['errors_count'],
        'createdAt': json['created_at'],
    };
}

export function UsageLogItemToJSON(json: any): UsageLogItem {
    return UsageLogItemToJSONTyped(json, false);
}

export function UsageLogItemToJSONTyped(value?: UsageLogItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'endpoint': value['endpoint'],
        'credits_cost': value['creditsCost'],
        'status': value['status'],
        'errors_count': value['errorsCount'],
        'created_at': value['createdAt'],
    };
}

