/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookItem } from './WebhookItem';
import {
    WebhookItemFromJSON,
    WebhookItemFromJSONTyped,
    WebhookItemToJSON,
    WebhookItemToJSONTyped,
} from './WebhookItem';

/**
 * 
 * @export
 * @interface WebhookListResponse
 */
export interface WebhookListResponse {
    /**
     * 
     */
    data: Array<WebhookItem>;
    /**
     * 
     */
    page: number;
    /**
     * 
     */
    limit: number;
}

/**
 * Check if a given object implements the WebhookListResponse interface.
 */
export function instanceOfWebhookListResponse(value: object): value is WebhookListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function WebhookListResponseFromJSON(json: any): WebhookListResponse {
    return WebhookListResponseFromJSONTyped(json, false);
}

export function WebhookListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WebhookItemFromJSON)),
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function WebhookListResponseToJSON(json: any): WebhookListResponse {
    return WebhookListResponseToJSONTyped(json, false);
}

export function WebhookListResponseToJSONTyped(value?: WebhookListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(WebhookItemToJSON)),
        'page': value['page'],
        'limit': value['limit'],
    };
}

