/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookItem
 */
export interface WebhookItem {
    /**
     * Webhook id
     */
    id: string;
    /**
     * Owner user id
     */
    userId: string;
    /**
     * Webhook name
     */
    name: string;
    /**
     * Destination URL
     */
    url: string;
    /**
     * HMAC signing secret
     */
    secret: string;
    /**
     * Subscribed events
     */
    events: Array<string>;
    /**
     * Is active
     */
    active: boolean;
    /**
     * Retry enabled
     */
    retryEnabled: boolean;
    /**
     * ISO 8601 of last delivery
     */
    lastDeliveryAt?: string;
    /**
     * Last HTTP status delivered
     */
    lastStatus?: number;
    /**
     * Consecutive failures
     */
    failureCount?: number;
    /**
     * ISO 8601 created
     */
    createdAt: string;
    /**
     * ISO 8601 updated
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the WebhookItem interface.
 */
export function instanceOfWebhookItem(value: object): value is WebhookItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('userId' in (value as Record<string, any>)) && !('user_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['userId'] === undefined && (value as Record<string, any>)['user_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if ((!('retryEnabled' in (value as Record<string, any>)) && !('retry_enabled' in (value as Record<string, any>))) || ((value as Record<string, any>)['retryEnabled'] === undefined && (value as Record<string, any>)['retry_enabled'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function WebhookItemFromJSON(json: any): WebhookItem {
    return WebhookItemFromJSONTyped(json, false);
}

export function WebhookItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'name': json['name'],
        'url': json['url'],
        'secret': json['secret'],
        'events': json['events'],
        'active': json['active'],
        'retryEnabled': json['retry_enabled'],
        'lastDeliveryAt': json['last_delivery_at'] == null ? undefined : json['last_delivery_at'],
        'lastStatus': json['last_status'] == null ? undefined : json['last_status'],
        'failureCount': json['failure_count'] == null ? undefined : json['failure_count'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function WebhookItemToJSON(json: any): WebhookItem {
    return WebhookItemToJSONTyped(json, false);
}

export function WebhookItemToJSONTyped(value?: WebhookItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'name': value['name'],
        'url': value['url'],
        'secret': value['secret'],
        'events': value['events'],
        'active': value['active'],
        'retry_enabled': value['retryEnabled'],
        'last_delivery_at': value['lastDeliveryAt'],
        'last_status': value['lastStatus'],
        'failure_count': value['failureCount'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

