/* tslint:disable */
/* eslint-disable */
/**
 * FalaAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebhookEvent = {
    SubscriptionCreated: 'subscription.created',
    AvulsoCompleted: 'avulso.completed',
    SubscriptionUpgraded: 'subscription.upgraded',
    SubscriptionDowngraded: 'subscription.downgraded',
    SubscriptionCanceled: 'subscription.canceled',
    CreditsLow: 'credits.low',
    CreditsExhausted: 'credits.exhausted',
    SubscriptionRenewed: 'subscription.renewed',
    SubscriptionExpired: 'subscription.expired',
    PaymentFailed: 'payment.failed',
} as const;
export type WebhookEvent = typeof WebhookEvent[keyof typeof WebhookEvent];


export function instanceOfWebhookEvent(value: any): boolean {
    for (const key in WebhookEvent) {
        if (Object.prototype.hasOwnProperty.call(WebhookEvent, key)) {
            if (WebhookEvent[key as keyof typeof WebhookEvent] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebhookEventFromJSON(json: any): WebhookEvent {
    return WebhookEventFromJSONTyped(json, false);
}

export function WebhookEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEvent {
    return json as WebhookEvent;
}

export function WebhookEventToJSON(value?: WebhookEvent | null): any {
    return value as any;
}

export function WebhookEventToJSONTyped(value: any, ignoreDiscriminator: boolean): WebhookEvent {
    return value as WebhookEvent;
}

