/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/audio/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe audio to text
         * @description Upload an audio file and receive transcription with speaker diarization, audio events, and dialog.
         *
         *     **Supported formats:** .mp3, .mp4, .m4a, .wav, .flac, .ogg, .webm, .aac, .opus
         *
         *     **Limits:**
         *     - Maximum audio duration: 3 hours
         *     - Maximum file size: 1GB
         *     - Cost: 1 credit per second of audio (rounded up), minimum 1 credit
         *
         *     **Supported languages:** pt, en, es, fr, de, it, ja, ko, nl, pl, ru, tr, zh, vi, id, th, ar, hi, cs, da, el, fi, he, hu, ms, no, ro, sk, sv, ta, uk
         *
         *     **Python:**
         *     ```python
         *     import httpx
         *
         *     response = httpx.post(
         *         'https://api.fala.ai/v1/audio/transcriptions',
         *         headers={'Authorization': 'Bearer fai_xxx'},
         *         files={'file': open('call.mp3', 'rb')},
         *         data={'model': 'falaai-transcribe-1', 'language': 'pt'}
         *     )
         *     print(response.json())
         *     ```
         *
         *     **cURL:**
         *     ```bash
         *     curl https://api.fala.ai/v1/audio/transcriptions \
         *       -H 'Authorization: Bearer fai_xxx' \
         *       -F 'file=@call.mp3' \
         *       -F 'model=falaai-transcribe-1' \
         *       -F 'language=pt'
         *     ```
         */
        post: operations["create_transcription_v1_audio_transcriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze/diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze a call transcript â€” 5 parallel analyses
         * @description Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.
         *
         *     **Python:**
         *     ```python
         *     import httpx
         *
         *     response = httpx.post(
         *         'https://api.fala.ai/v1/analyze/diagnostic',
         *         headers={'Authorization': 'Bearer fai_xxx'},
         *         json={
         *             'dialog': 'Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.',
         *             'language': 'pt-BR',
         *             'duration_seconds': 151.0
         *         }
         *     )
         *     print(response.json())
         *     ```
         *
         *     **cURL:**
         *     ```bash
         *     curl https://api.fala.ai/v1/analyze/diagnostic \
         *       -H 'Authorization: Bearer fai_xxx' \
         *       -H 'Content-Type: application/json' \
         *       -d '{
         *         "dialog": "Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.",
         *         "language": "pt-BR",
         *         "duration_seconds": 151.0
         *       }'
         *     ```
         */
        post: operations["create_diagnostic_v1_analyze_diagnostic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze/auditoriaRisco": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compliance Risk Audit â€” conversation compliance analysis
         * @description Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.
         *
         *     **Python:**
         *     ```python
         *     import httpx
         *
         *     response = httpx.post(
         *         'https://api.fala.ai/v1/analyze/auditoriaRisco',
         *         headers={'Authorization': 'Bearer fai_xxx'},
         *         json={
         *             'dialog': 'Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.',
         *             'duration_seconds': 151.0,
         *             'language': 'pt-BR',
         *             'response_language': 'en-US'
         *         }
         *     )
         *     print(response.json())
         *     ```
         *
         *     **cURL:**
         *     ```bash
         *     curl https://api.fala.ai/v1/analyze/auditoriaRisco \
         *       -H 'Authorization: Bearer fai_xxx' \
         *       -H 'Content-Type: application/json' \
         *       -d '{
         *         "dialog": "Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.",
         *         "duration_seconds": 151.0,
         *         "language": "pt-BR",
         *         "response_language": "en-US"
         *       }'
         *     ```
         */
        post: operations["create_auditoria_risco_v1_analyze_auditoriaRisco_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage Log */
        get: operations["get_usage_log_v1_usage_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/by-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage By Key */
        get: operations["get_usage_by_key_v1_usage_by_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar webhooks de alertas
         * @description Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
         */
        get: operations["list_webhooks_v1_webhooks_get"];
        put?: never;
        /**
         * Criar webhook de alertas
         * @description Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de "timestamp.body" com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
         */
        post: operations["create_webhook_v1_webhooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Atualizar webhook
         * @description Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
         */
        put: operations["update_webhook_v1_webhooks__webhook_id__put"];
        post?: never;
        /**
         * Remover webhook
         * @description Remove inscricao de webhook por ID.
         */
        delete: operations["delete_webhook_v1_webhooks__webhook_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/email-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar emails de alerta */
        get: operations["list_email_alerts_v1_email_alerts_get"];
        put?: never;
        /** Criar email de alerta */
        post: operations["create_email_alert_v1_email_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/email-alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualizar email de alerta */
        put: operations["update_email_alert_v1_email_alerts__alert_id__put"];
        post?: never;
        /** Remover email de alerta */
        delete: operations["delete_email_alert_v1_email_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Health Check */
        head: operations["health_check_head"];
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioEvent */
        AudioEvent: {
            /**
             * Event
             * @description Type of identified audio event. Ex: [riso], [suspiro], [pausa], [tosse]
             * @example [suspiro]
             */
            event: string;
            /**
             * Start S
             * @description Start time of audio event in seconds
             * @example 75.42
             */
            start_s: number;
            /**
             * End S
             * @description End time of audio event in seconds
             * @example 75.43
             */
            end_s: number;
            /**
             * Duration S
             * @description Event duration in seconds
             * @example 0.01
             */
            duration_s: number;
            /**
             * Formatted Timestamp
             * @description Formatted timestamp HH:MM:SS.mmm of event start
             * @example 00:01:15.420
             */
            formatted_timestamp: string;
        };
        /** AudioInputMeta */
        AudioInputMeta: {
            /**
             * Duration S
             * @description Exact audio duration sent in seconds
             * @example 151.04
             */
            duration_s: number;
            /**
             * Original Format
             * @description Original file format (wav, mp3, ogg, etc)
             * @example wav
             */
            original_format: string;
            /**
             * Codec
             * @description Audio codec sent
             * @example pcm_s16le
             */
            codec: string;
            /**
             * Sample Rate
             * @description Audio sample rate in Hz
             * @example 44100
             */
            sample_rate: number;
            /**
             * Channels
             * @description Number of channels (1=mono, 2=stereo)
             * @example 2
             */
            channels: number;
        };
        /** AuditoriaRiscoAnalysisV2 */
        AuditoriaRiscoAnalysisV2: {
            /**
             * Global Metrics
             * @description Global metrics
             * @default {}
             */
            global_metrics: {
                [key: string]: unknown;
            };
            /**
             * Final Analysis
             * @description Final analysis
             * @default {}
             */
            final_analysis: {
                [key: string]: unknown;
            };
            /**
             * Frameworks
             * @description Frameworks (COPC/ISO/Kirkpatrick/CES)
             * @default {}
             */
            frameworks: {
                [key: string]: unknown;
            };
        };
        /** AuditoriaRiscoAppliedActionV2 */
        AuditoriaRiscoAppliedActionV2: {
            /**
             * Action Type
             * @description Action type code
             */
            action_type: string;
            /**
             * Label
             * @description Action label
             */
            label: string;
            /**
             * Description
             * @description Action description
             */
            description: string;
            /**
             * Priority
             * @description CRITICO/ALTO/MEDIO/BAIXO
             */
            priority: string;
            /**
             * Color
             * @description Color
             * @default
             */
            color: string;
            /**
             * Icon
             * @description Icon
             * @default
             */
            icon: string;
            /**
             * Condition
             * @description Condition
             */
            condition?: string | null;
            /**
             * Reason
             * @description Reason
             * @default
             */
            reason: string;
        };
        /** AuditoriaRiscoAudioEventModelV2 */
        AuditoriaRiscoAudioEventModelV2: {
            /**
             * Model
             * @description MAC model text (i18n)
             * @default
             */
            model: string;
            /**
             * Description
             * @description MAC description (i18n)
             * @default
             */
            description: string;
            /**
             * Windows S
             * @description Temporal windows (s)
             * @default {}
             */
            windows_s: {
                [key: string]: unknown;
            };
        };
        /** AuditoriaRiscoAuditDecisionsV2 */
        AuditoriaRiscoAuditDecisionsV2: {
            /**
             * Risk Origin
             * @description Risk origin
             */
            risk_origin?: string | null;
            /**
             * Has Zero Tolerance Violation
             * @description Has zero-tolerance violation
             */
            has_zero_tolerance_violation?: boolean | null;
            /**
             * Deterministic Validator Changes
             * @description Deterministic validator changes
             * @default []
             */
            deterministic_validator_changes: unknown[];
        };
        /** AuditoriaRiscoConversationScoresV2 */
        AuditoriaRiscoConversationScoresV2: {
            /**
             * Consolidated Score
             * @description Consolidated score
             */
            consolidated_score?: number | null;
            /**
             * Violation Density Per Min
             * @description Violation density/min
             */
            violation_density_per_min?: number | null;
            /**
             * Sentiment Trend
             * @description Sentiment trend
             */
            sentiment_trend?: unknown | null;
            /**
             * Pct Turns With Violation
             * @description % turns with violation
             */
            pct_turns_with_violation?: number | null;
            /**
             * Most Critical Turn
             * @description Most critical turn
             */
            most_critical_turn?: unknown | null;
            /**
             * Positive Negative Ratio
             * @description Positive:negative ratio
             */
            positive_negative_ratio?: unknown | null;
            /**
             * Global Risk Severity
             * @description Global risk severity code
             */
            global_risk_severity?: string | null;
            /**
             * Global Risk Severity Label
             * @description Global risk severity label
             */
            global_risk_severity_label?: string | null;
            /**
             * Global Risk Severity Color
             * @description Global risk severity color
             */
            global_risk_severity_color?: string | null;
            /**
             * Risk Likelihood Avg
             * @description Risk likelihood avg
             */
            risk_likelihood_avg?: number | null;
            /**
             * Risk Impact Avg
             * @description Risk impact avg
             */
            risk_impact_avg?: number | null;
        };
        /** AuditoriaRiscoDetectionItemV2 */
        AuditoriaRiscoDetectionItemV2: {
            /**
             * Turn
             * @description Turn number
             */
            turn?: number | null;
            /**
             * Interlocutor
             * @description Speaker
             */
            interlocutor?: string | null;
            /**
             * Role
             * @description Role
             */
            role?: string | null;
            /**
             * Timestamp Start S
             * @description Start (s)
             */
            timestamp_start_s?: number | null;
            /**
             * Timestamp End S
             * @description End (s)
             */
            timestamp_end_s?: number | null;
            /**
             * Timestamp Formatted
             * @description Formatted timestamp
             */
            timestamp_formatted?: string | null;
            /**
             * Term Text
             * @description Detected term
             */
            term_text?: string | null;
            /**
             * Suggested Term For Bank
             * @description Suggested term for bank
             */
            suggested_term_for_bank?: unknown | null;
            /**
             * Category
             * @description Category code
             */
            category?: string | null;
            /**
             * Category Label
             * @description Category label (i18n)
             */
            category_label: string;
            /**
             * Category Color
             * @description Category color
             */
            category_color?: string | null;
            /**
             * Category Icon
             * @description Category icon
             */
            category_icon?: string | null;
            /**
             * Criticality
             * @description Criticality
             */
            criticality?: string | null;
            /**
             * Category Threshold
             * @description Category threshold
             */
            category_threshold?: number | null;
            /**
             * Category Type
             * @description Category type
             */
            category_type?: string | null;
            /**
             * Category Group
             * @description Category group label (i18n)
             */
            category_group: string;
            /**
             * Nature
             * @description Nature
             */
            nature?: string | null;
            /**
             * Llm Confidence
             * @description LLM confidence
             */
            llm_confidence?: number | null;
            /**
             * Reason
             * @description Reason
             */
            reason?: string | null;
            /**
             * Is Valid Context
             * @description Valid context
             */
            is_valid_context?: boolean | null;
            /**
             * Risk Probability
             * @description Risk probability
             */
            risk_probability?: number | null;
            /**
             * Risk Impact
             * @description Risk impact
             */
            risk_impact?: number | null;
            /**
             * Category Weight
             * @description Category weight
             */
            category_weight?: number | null;
            /**
             * Turn Sentiment
             * @description Turn sentiment
             */
            turn_sentiment?: string | null;
            /**
             * Intensity
             * @description Intensity
             */
            intensity?: unknown | null;
            /**
             * Mod Applied
             * @description Total modifier applied
             */
            mod_applied?: number | null;
            /**
             * Mac Applied
             * @description Audio modifier applied
             */
            mac_applied?: number | null;
            /**
             * Mvad Applied
             * @description Intensity modifier applied
             */
            mvad_applied?: number | null;
            /**
             * Mod Formula
             * @description Modifier formula
             */
            mod_formula?: string | null;
            /**
             * Mac Details
             * @description MAC details
             * @default []
             */
            mac_details: {
                [key: string]: unknown;
            }[];
            /**
             * Calibration Reason
             * @description Calibration reason
             */
            calibration_reason?: string | null;
            /**
             * Final Score
             * @description Final score
             */
            final_score?: number | null;
            /**
             * Final Score Formula
             * @description Final score formula
             */
            final_score_formula?: string | null;
            /**
             * Conversation Limit
             * @description Conversation limit
             */
            conversation_limit?: unknown | null;
            /**
             * Apply Saturation
             * @description Apply saturation
             */
            apply_saturation?: boolean | null;
            /**
             * Block Repetition
             * @description Block repetition
             */
            block_repetition?: boolean | null;
            /**
             * Status
             * @description Status
             */
            status?: string | null;
            /**
             * Effective Impact
             * @description Effective impact
             */
            effective_impact?: number | null;
            /**
             * Saturation Factor
             * @description Saturation factor
             */
            saturation_factor?: number | null;
            /**
             * Saturation Formula
             * @description Saturation formula
             */
            saturation_formula?: string | null;
            /**
             * Threshold Formula
             * @description Threshold formula
             */
            threshold_formula?: string | null;
            /**
             * Blocked Formula
             * @description Blocked formula
             */
            blocked_formula?: string | null;
            /**
             * Reconciliation Note
             * @description Reconciliation note
             */
            reconciliation_note?: string | null;
            /**
             * Violated Frameworks
             * @description Violated frameworks
             * @default []
             */
            violated_frameworks: unknown[];
            /**
             * Citation Fidelity
             * @description Citation fidelity
             * @default true
             */
            citation_fidelity: boolean;
            /**
             * Subcategory
             * @description Subcategory code
             */
            subcategory?: string | null;
            /**
             * Subcategory Label
             * @description Subcategory label (i18n)
             */
            subcategory_label?: string | null;
        };
        /** AuditoriaRiscoDetectionsV2 */
        AuditoriaRiscoDetectionsV2: {
            /**
             * Violations
             * @description Active violations
             * @default []
             */
            violations: components["schemas"]["AuditoriaRiscoDetectionItemV2"][];
            /**
             * Positives
             * @description Active positives
             * @default []
             */
            positives: components["schemas"]["AuditoriaRiscoDetectionItemV2"][];
            /**
             * Client Risk Alerts
             * @description Client risk alerts
             * @default []
             */
            client_risk_alerts: {
                [key: string]: unknown;
            }[];
            /**
             * Client Behavior Alerts
             * @description Client behavior alerts
             * @default []
             */
            client_behavior_alerts: {
                [key: string]: unknown;
            }[];
            /**
             * Client Negatives
             * @description Client negatives
             * @default []
             */
            client_negatives: components["schemas"]["AuditoriaRiscoDetectionItemV2"][];
        };
        /** AuditoriaRiscoIndexerV2 */
        AuditoriaRiscoIndexerV2: {
            /**
             * Suggested Terms For Bank
             * @description Suggested terms for bank
             * @default []
             */
            suggested_terms_for_bank: {
                [key: string]: unknown;
            }[];
        };
        /** AuditoriaRiscoMetaV2 */
        AuditoriaRiscoMetaV2: {
            /**
             * Id
             * @description Analysis id
             */
            id: string;
            /**
             * Object
             * @description Object type
             * @default auditoria_risco
             */
            object: string;
            /**
             * Call Duration S
             * @description Call duration (s)
             */
            call_duration_s?: number | null;
            /**
             * Analyzed At
             * @description ISO 8601 analyzed timestamp
             */
            analyzed_at?: string | null;
            /** @description Usage block */
            usage: components["schemas"]["AuditoriaRiscoUsageV2"];
            /**
             * Client Reference Id
             * @description Echoed client reference id
             */
            client_reference_id?: string | null;
        };
        /** AuditoriaRiscoParticipantV2 */
        AuditoriaRiscoParticipantV2: {
            /**
             * Interlocutor
             * @description Speaker label
             */
            interlocutor?: string | null;
            /**
             * Name
             * @description Participant name
             */
            name?: string | null;
            /**
             * Role
             * @description Role (agent/client/bot/unknown)
             */
            role?: string | null;
        };
        /** AuditoriaRiscoParticipantsV2 */
        AuditoriaRiscoParticipantsV2: {
            /**
             * Identified
             * @description Identified participants
             * @default []
             */
            identified: components["schemas"]["AuditoriaRiscoParticipantV2"][];
            /**
             * Call Direction
             * @description inbound/outbound
             */
            call_direction?: string | null;
            /**
             * Role Inference Reliable
             * @description Role inference reliability
             * @default true
             */
            role_inference_reliable: boolean;
            /**
             * Identification Status
             * @description Identification status
             * @default none
             */
            identification_status: string;
            /**
             * Unidentified Items Count
             * @description Unidentified items count
             * @default 0
             */
            unidentified_items_count: number;
        };
        /** AuditoriaRiscoRequest */
        AuditoriaRiscoRequest: {
            /**
             * Model
             * @description Analysis model. Always 'falaai-auditoria-risco-1'
             * @default falaai-auditoria-risco-1
             * @example falaai-auditoria-risco-1
             */
            model: string;
            /**
             * Text
             * @description Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters
             * @default
             */
            text: string;
            /**
             * Dialog
             * @description Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters
             * @default
             * @example Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.
             */
            dialog: string;
            /**
             * Audio Events
             * @description Audio events with timestamps (correlated with turns when diarization is present)
             * @default []
             */
            audio_events: components["schemas"]["DiagnosticAudioEvent"][];
            /**
             * Duration Seconds
             * @description Total audio duration in seconds. Required. Max 3h (10800s).
             */
            duration_seconds: number;
            /**
             * Language
             * @description Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES.
             * @example pt-BR
             */
            language: string;
            /**
             * Response Language
             * @description Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from 'language'. Accepted: pt-BR, en-US, es-ES.
             * @example en-US
             */
            response_language: string;
            /**
             * Call Direction
             * @description Who originated the call. inbound=client called, outbound=company called. If omitted, LLM infers from context.
             * @example inbound
             */
            call_direction?: ("inbound" | "outbound") | null;
            /**
             * Participants
             * @description Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth â€” no inference.
             * @example [
             *       {
             *         "interlocutor": "Interlocutor 1",
             *         "name": "Antonio",
             *         "role": "client"
             *       },
             *       {
             *         "interlocutor": "Interlocutor 2",
             *         "name": "Maria",
             *         "role": "agent"
             *       }
             *     ]
             */
            participants?: components["schemas"]["Participant"][] | null;
            /**
             * Response Format
             * @description Response format version. v1=legacy flat PT-BR, v2=structured EN-US blocks.
             * @default v2
             * @example v2
             */
            response_format: string;
            /**
             * Client Reference Id
             * @description Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
             * @example call-2026-08-30-001
             */
            client_reference_id?: string | null;
        };
        /** AuditoriaRiscoScoresV2 */
        AuditoriaRiscoScoresV2: {
            /** @description Conversation scores */
            conversation: components["schemas"]["AuditoriaRiscoConversationScoresV2"];
            /**
             * Per Participant
             * @description Per-participant KPIs
             * @default {}
             */
            per_participant: {
                [key: string]: unknown;
            };
        };
        /** AuditoriaRiscoScoringExplanationV2 */
        AuditoriaRiscoScoringExplanationV2: {
            /**
             * Summary
             * @description Explanation summary
             */
            summary?: string | null;
            /**
             * Steps
             * @description Explanation steps
             * @default []
             */
            steps: unknown[];
        };
        /** AuditoriaRiscoSummaryV2 */
        AuditoriaRiscoSummaryV2: {
            /**
             * Total Turns
             * @description Total turns
             */
            total_turns?: number | null;
            /**
             * Total Calibrated
             * @description Total calibrated detections
             */
            total_calibrated?: number | null;
            /**
             * Active
             * @description Active detections
             */
            active?: number | null;
            /**
             * Tolerated
             * @description Tolerated detections
             */
            tolerated?: number | null;
            /**
             * Blocked
             * @description Blocked detections
             */
            blocked?: number | null;
            /**
             * Audio Events Used
             * @description Audio events used
             */
            audio_events_used?: number | null;
            /**
             * Audio Events Aggravated
             * @description Audio events aggravated
             */
            audio_events_aggravated?: number | null;
            /**
             * Mac Audio Applied
             * @description MAC audio applied
             */
            mac_audio_applied?: unknown | null;
            /**
             * Mvad Applied
             * @description MVAD applied
             */
            mvad_applied?: unknown | null;
            /**
             * Total Participants
             * @description Total participants
             */
            total_participants?: number | null;
            /**
             * Total Agents
             * @description Total agents
             */
            total_agents?: number | null;
            /**
             * Total Clients
             * @description Total clients
             */
            total_clients?: number | null;
            /**
             * Total Bots
             * @description Total bots
             */
            total_bots?: number | null;
            /**
             * Total Unknown
             * @description Total unknown
             */
            total_unknown?: number | null;
            /**
             * Client Risk Alerts Count
             * @description Client risk alerts count
             */
            client_risk_alerts_count?: number | null;
            /**
             * Client Behavior Alerts Count
             * @description Client behavior alerts count
             */
            client_behavior_alerts_count?: number | null;
        };
        /** AuditoriaRiscoTimelineV2 */
        AuditoriaRiscoTimelineV2: {
            /**
             * Turns Sentiment
             * @description Per-turn sentiment
             * @default []
             */
            turns_sentiment: {
                [key: string]: unknown;
            }[];
            /**
             * Audio Events
             * @description Audio events (i18n)
             * @default []
             */
            audio_events: {
                [key: string]: unknown;
            }[];
            /**
             * Audio Groups Found
             * @description Audio groups found
             * @default []
             */
            audio_groups_found: {
                [key: string]: unknown;
            }[];
        };
        /** AuditoriaRiscoUsageV2 */
        AuditoriaRiscoUsageV2: {
            /**
             * Characters
             * @description Characters analyzed
             */
            characters: number;
            /**
             * Credits Consumed
             * @description Credits consumed
             */
            credits_consumed: number;
            /**
             * Processing Ms
             * @description Processing time (ms)
             */
            processing_ms: number;
        };
        /**
         * AuditoriaRiscoV2
         * @description Response V2 (build_public_response_v2) â€” blocos logicos EN-US. Fonte: response_builder.py.
         */
        AuditoriaRiscoV2: {
            /** @description Identification + usage */
            meta: components["schemas"]["AuditoriaRiscoMetaV2"];
            /** @description Participants/roles/direction */
            participants: components["schemas"]["AuditoriaRiscoParticipantsV2"];
            /** @description Verdict + level + applied actions */
            verdict: components["schemas"]["AuditoriaRiscoVerdictV2"];
            /** @description Consolidated + per-participant scores */
            scores: components["schemas"]["AuditoriaRiscoScoresV2"];
            /** @description violations/positives/client alerts */
            detections: components["schemas"]["AuditoriaRiscoDetectionsV2"];
            /** @description global_metrics + final_analysis + frameworks */
            analysis: components["schemas"]["AuditoriaRiscoAnalysisV2"];
            /** @description turns_sentiment + audio_events + groups */
            timeline: components["schemas"]["AuditoriaRiscoTimelineV2"];
            /** @description MAC audio event semantics */
            audio_event_model: components["schemas"]["AuditoriaRiscoAudioEventModelV2"];
            /**
             * Categories Summary
             * @description Per-category summary (keyed by category)
             */
            categories_summary: {
                [key: string]: unknown;
            };
            /** @description Suggested terms for bank */
            indexer: components["schemas"]["AuditoriaRiscoIndexerV2"];
            /** @description Executive summary counts */
            summary: components["schemas"]["AuditoriaRiscoSummaryV2"];
            /**
             * Acoes I18N
             * @description Used actions i18n catalog (keyed by action)
             */
            acoes_i18n: {
                [key: string]: unknown;
            };
            /** @description Risk origin + validator changes */
            audit_decisions: components["schemas"]["AuditoriaRiscoAuditDecisionsV2"];
            /** @description Score composition explanation */
            scoring_explanation: components["schemas"]["AuditoriaRiscoScoringExplanationV2"];
            /**
             * Html Report
             * @description HTML report (base64 gzip)
             */
            html_report: string;
        };
        /** AuditoriaRiscoV2Response */
        AuditoriaRiscoV2Response: {
            /** @description Public response V2 â€” always returned */
            response: components["schemas"]["AuditoriaRiscoV2"];
        };
        /** AuditoriaRiscoVerdictV2 */
        AuditoriaRiscoVerdictV2: {
            /**
             * Label
             * @description Human-readable verdict
             */
            label?: string | null;
            /**
             * Level Code
             * @description Classification level code
             */
            level_code?: string | null;
            /**
             * Color
             * @description Level color
             */
            color?: string | null;
            /**
             * Icon
             * @description Level icon
             */
            icon?: string | null;
            /**
             * Risk Matrix
             * @description Risk matrix
             * @default {}
             */
            risk_matrix: {
                [key: string]: unknown;
            };
            /**
             * Applied Actions
             * @description Applied actions
             * @default []
             */
            applied_actions: components["schemas"]["AuditoriaRiscoAppliedActionV2"][];
            /**
             * Decision Details
             * @description Decision details
             */
            decision_details?: unknown | null;
        };
        /** Body_create_transcription_v1_audio_transcriptions_post */
        Body_create_transcription_v1_audio_transcriptions_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Model
             * @default falaai-transcribe-1
             */
            model: string;
            /**
             * Language
             * @default pt
             */
            language: string;
            /**
             * Client Reference Id
             * @description Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency.
             */
            client_reference_id?: string;
        };
        /** CreateEmailAlertRequest */
        CreateEmailAlertRequest: {
            /**
             * Name
             * @description Nome identificador
             * @example Financeiro
             */
            name: string;
            /**
             * Email
             * @description Email destino
             * @example finance@empresa.com
             */
            email: string;
            /**
             * Events
             * @description Eventos subscritos
             * @example [
             *       "payment.failed",
             *       "subscription.renewed"
             *     ]
             */
            events: components["schemas"]["EmailEvent"][];
        };
        /** CreateWebhookRequest */
        CreateWebhookRequest: {
            /**
             * Name
             * @description Nome identificador do webhook
             * @example Alertas FalaAI
             */
            name: string;
            /**
             * Url
             * @description URL HTTPS que recebera POST com HMAC FalaAI-Signature
             * @example https://webhook.site/00000000-0000-0000-0000-000000000000
             */
            url: string;
            /**
             * Events
             * @description Eventos subscritos (10 alertas)
             * @example [
             *       "credits.low",
             *       "credits.exhausted",
             *       "payment.failed"
             *     ]
             */
            events: components["schemas"]["WebhookEvent"][];
            /**
             * Retry Enabled
             * @description Retry exponencial 5 tentativas quando true (false=1 tentativa)
             * @default false
             * @example false
             */
            retry_enabled: boolean;
        };
        /** DiagnosticAnalysisMap */
        DiagnosticAnalysisMap: {
            /** @description Detailed conversation summary */
            dialogue_summary: components["schemas"]["DiagnosticTextAnalysis"];
            /** @description Initial contact reason */
            contact_reason: components["schemas"]["DiagnosticTextAnalysis"];
            /** @description Action taken / resolution */
            identified_action: components["schemas"]["DiagnosticCategoricalAnalysis"];
            /** @description Theme classification */
            identified_label: components["schemas"]["DiagnosticCategoricalAnalysis"];
            /** @description Predominant sentiment */
            sentiment: components["schemas"]["DiagnosticCategoricalAnalysis"];
            /**
             * Participants Identified
             * @description Identified participants and roles (same field names as auditoria)
             * @default []
             */
            participants_identified: components["schemas"]["ParticipantDiagnostic"][];
        };
        /** DiagnosticAudioEvent */
        DiagnosticAudioEvent: {
            /**
             * Event
             * @description Audio event type. E.g.: [laughter], [sigh]
             * @example [laughter]
             */
            event: string;
            /**
             * Start S
             * @description Start time in seconds
             * @example 72.98
             */
            start_s?: number | null;
            /**
             * End S
             * @description End time in seconds
             * @example 74.34
             */
            end_s?: number | null;
            /**
             * Duration S
             * @description Duration in seconds
             * @example 1.36
             */
            duration_s?: number | null;
            /**
             * Formatted Timestamp
             * @description Formatted timestamp (HH:MM:SS.ms)
             * @example 00:01:12.980
             */
            formatted_timestamp?: string | null;
        };
        /** DiagnosticCategoricalAnalysis */
        DiagnosticCategoricalAnalysis: {
            /**
             * List Choice
             * @description Selected value from classification list (used in action, label, sentiment)
             * @example Informative
             */
            list_choice?: string | null;
            /**
             * Justification
             * @description Justification for the choice
             * @example Information about required documentation was provided
             */
            justification?: string | null;
            /**
             * Evidence Phrases
             * @description Verbatim transcript excerpts supporting the analysis
             * @default []
             * @example [
             *       "[00:01:36.640 - 00:02:02.659] No, same thing: proof of address..."
             *     ]
             */
            evidence_phrases: string[];
        };
        /** DiagnosticRequest */
        DiagnosticRequest: {
            /**
             * Model
             * @description Analysis model. Always 'falaai-diagnostic-1'
             * @default falaai-diagnostic-1
             * @example falaai-diagnostic-1
             */
            model: string;
            /**
             * Text
             * @description Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters
             * @default
             */
            text: string;
            /**
             * Dialog
             * @description Diarized transcript with speaker turns. PRIMARY source. At least one of 'dialog' or 'text' required. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters
             * @default
             * @example Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.
             */
            dialog: string;
            /**
             * Audio Events
             * @description Detected audio events with timestamps (required when using dialog)
             * @default []
             */
            audio_events: components["schemas"]["DiagnosticAudioEvent"][];
            /**
             * Language
             * @description Transcript language. Required. Accepted: en-US, pt-BR, es-ES, es-MX, fr-FR, de-DE, it-IT, pt-PT, zh-CN, ja-JP, ko-KR, ar-SA, hi-IN, ru-RU, id-ID, tr-TR, nl-NL, pl-PL, vi-VN, th-TH, en-GB
             * @example pt-BR
             */
            language: string;
            /**
             * Duration Seconds
             * @description Total audio duration in seconds. Required. Max 3h (10800s).
             */
            duration_seconds: number;
            /**
             * Client Reference Id
             * @description Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
             * @example call-2026-08-30-001
             */
            client_reference_id?: string | null;
        };
        /** DiagnosticResponse */
        DiagnosticResponse: {
            /**
             * Id
             * @description Unique analysis identifier. Prefix 'di-' + UUID
             * @example di-550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Response Language
             * @description Language used in the response. E.g.: 'pt-BR', 'en-US', 'es-ES'
             * @example pt-BR
             */
            response_language: string;
            /**
             * Object
             * @description Object type. Always 'analysis'
             * @example analysis
             */
            object: string;
            /** @description The 6 conversation analyses (5 + participants) */
            analysis: components["schemas"]["DiagnosticAnalysisMap"];
            /** @description Usage and processing information */
            usage: components["schemas"]["DiagnosticUsage"];
            /**
             * Client Reference Id
             * @description Client-supplied ID echoed verbatim (if provided in request)
             * @example call-2026-08-30-001
             */
            client_reference_id?: string | null;
        };
        /** DiagnosticTextAnalysis */
        DiagnosticTextAnalysis: {
            /**
             * Explanation
             * @description Explanatory text (used in summary and reason)
             * @example Speaker 1 provided guidance on documentation...
             */
            explanation?: string | null;
        };
        /** DiagnosticUsage */
        DiagnosticUsage: {
            /**
             * Characters
             * @description Total characters analyzed
             * @example 3946
             */
            characters: number;
            /**
             * Credits Consumed
             * @description Credits consumed: max(ceil(chars/500)*3, 3) * 5
             * @example 15
             */
            credits_consumed: number;
            /**
             * Processing Ms
             * @description Total processing time in milliseconds
             * @example 6800
             */
            processing_ms: number;
        };
        /** EmailAlertItem */
        EmailAlertItem: {
            /**
             * Id
             * @description Email alert id
             */
            id: string;
            /**
             * User Id
             * @description Owner user id
             */
            user_id: string;
            /**
             * Name
             * @description Email alert name
             */
            name: string;
            /**
             * Email
             * @description Destination email
             */
            email: string;
            /**
             * Events
             * @description Subscribed events
             */
            events: string[];
            /**
             * Active
             * @description Is active
             */
            active: boolean;
            /**
             * Created At
             * @description ISO 8601 created
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO 8601 updated
             */
            updated_at: string;
        };
        /** EmailAlertListResponse */
        EmailAlertListResponse: {
            /** Data */
            data: components["schemas"]["EmailAlertItem"][];
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /** EmailAlertMessageResponse */
        EmailAlertMessageResponse: {
            /**
             * Message
             * @description Operation result message
             */
            message: string;
        };
        /**
         * EmailEvent
         * @enum {string}
         */
        EmailEvent: "subscription.created" | "avulso.completed" | "subscription.upgraded" | "subscription.downgraded" | "subscription.canceled" | "credits.low" | "credits.exhausted" | "subscription.renewed" | "payment.failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Overall API status
             * @example ok
             */
            status: string;
            /**
             * Version
             * @description Current API version
             * @example api_v1.5.2
             */
            version: string;
            /**
             * Uptime Seconds
             * @description Uptime in seconds
             * @example 3600
             */
            uptime_seconds: number;
            /**
             * Database
             * @description Database connection status
             * @example true
             */
            database: boolean;
            /**
             * Phase
             * @description Development phase
             * @example development
             */
            phase: string;
            /**
             * Launch Date
             * @description Expected public launch date
             * @example 2026-08-01
             */
            launch_date: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Message
             * @description Operation result message
             */
            message: string;
        };
        /** Participant */
        Participant: {
            /**
             * Interlocutor
             * @description Exact identifier as used in dialog (e.g. 'Interlocutor 1', 'Antonio')
             * @example Interlocutor 1
             */
            interlocutor: string;
            /**
             * Name
             * @description Participant name (humanizes report, does not affect logic)
             * @example Maria
             */
            name?: string | null;
            /**
             * Role
             * @description Role: agent (human operator), client (customer), bot (IVR/AI)
             * @enum {string}
             */
            role: "agent" | "client" | "bot";
        };
        /** ParticipantDiagnostic */
        ParticipantDiagnostic: {
            /**
             * Interlocutor
             * @description Exact speaker label from the dialog (e.g. 'Speaker 1')
             * @example Speaker 1
             */
            interlocutor: string;
            /**
             * Role
             * @description Role: agent | client | bot | agent_requester | agent_custodian
             * @example client
             */
            role: string;
            /**
             * Name
             * @description Participant name if mentioned in the dialogue
             * @example AntÃ´nio
             */
            name?: string | null;
            /**
             * Confidence
             * @description high | medium | low
             * @example high
             */
            confidence?: string | null;
            /**
             * Evidence
             * @description Exact verbatim quote supporting the role (no timestamps)
             * @example TÃ¡ quarenta reais e setenta e um, AntÃ´nio.
             */
            evidence?: string | null;
        };
        /** TranscriptionResponse */
        TranscriptionResponse: {
            /**
             * Id
             * @description Unique transcription identifier. Prefix 'tr-' followed by UUID
             * @example tr-550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Object
             * @description Returned object type. Always 'transcription'
             * @example transcription
             */
            object: string;
            /**
             * Model
             * @description Model used for transcription. Ex: 'falaai-transcribe-1'
             * @example falaai-transcribe-1
             */
            model: string;
            /**
             * Filename
             * @description Original audio file name uploaded
             * @example chamada.mp3
             */
            filename: string;
            /**
             * Processed At
             * @description Processing datetime in ISO 8601 UTC format
             * @example 2026-06-25T01:00:35.399252+00:00
             */
            processed_at: string;
            /** @description Usage and processing information */
            usage: components["schemas"]["TranscriptionUsage"];
            /**
             * Language
             * @description ISO 639-3 language code detected in audio. Ex: 'por' (Portuguese), 'eng' (English), 'spa' (Spanish)
             * @example por
             */
            language: string;
            /**
             * Language Confidence
             * @description Language detection confidence level (0.0 to 1.0). Higher is more reliable
             * @example 1
             */
            language_confidence?: number | null;
            /**
             * Duration Seconds
             * @description Total audio duration in seconds
             * @example 151.04
             */
            duration_seconds: number;
            /**
             * Text
             * @description Full transcription as plain text, including audio events in brackets
             * @example Oi, Alex. Oi. O, Thais- Oi...
             */
            text: string;
            /**
             * Dialog
             * @description Turn-by-turn formatted transcript with speaker identification and start/end timestamps
             * @example Speaker 1: [00:00:00.540 - 00:00:01.139] Oi, Alex.
             *     Speaker 2: [00:00:01.940 - 00:00:02.720] Oi...
             */
            dialog: string;
            /**
             * Audio Events
             * @description List of detected audio events (laughs, sighs, pauses, etc) with timestamps and duration
             */
            audio_events: components["schemas"]["AudioEvent"][];
            /**
             * Event Types
             * @description Unique audio event types found in transcription, alphabetically sorted
             * @example [
             *       "[riso]",
             *       "[suspiro]"
             *     ]
             */
            event_types: string[];
            /**
             * Word Count
             * @description Total number of recognized words in transcription
             * @example 773
             */
            word_count: number;
            /** @description Metadados do arquivo de audio enviado (duracao, formato, codec, sample rate, canais) */
            input: components["schemas"]["AudioInputMeta"];
            /**
             * Client Reference Id
             * @description Client-supplied ID echoed verbatim (if provided in request)
             * @example call-2026-08-30-001
             */
            client_reference_id?: string | null;
        };
        /** TranscriptionUsage */
        TranscriptionUsage: {
            /**
             * Audio Seconds
             * @description Actual audio duration processed in seconds
             * @example 151.04
             */
            audio_seconds: number;
            /**
             * Credits Consumed
             * @description Number of credits consumed in this request
             * @example 65
             */
            credits_consumed: number;
            /**
             * Processing Ms
             * @description Total processing time in milliseconds
             * @example 15156
             */
            processing_ms: number;
        };
        /** UpdateEmailAlertRequest */
        UpdateEmailAlertRequest: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Events */
            events?: components["schemas"]["EmailEvent"][] | null;
            /** Active */
            active?: boolean | null;
        };
        /** UpdateWebhookRequest */
        UpdateWebhookRequest: {
            /**
             * Name
             * @description Nome identificador
             * @example Alertas FalaAI
             */
            name?: string | null;
            /**
             * Url
             * @description URL HTTPS destino
             * @example https://webhook.site/00000000-0000-0000-0000-000000000000
             */
            url?: string | null;
            /**
             * Events
             * @description Eventos subscritos
             * @example [
             *       "credits.low"
             *     ]
             */
            events?: components["schemas"]["WebhookEvent"][] | null;
            /**
             * Retry Enabled
             * @description Habilita retry exponencial
             * @example true
             */
            retry_enabled?: boolean | null;
            /**
             * Active
             * @description Ativa/desativa sem deletar
             * @example true
             */
            active?: boolean | null;
        };
        /** UsageByKeyItem */
        UsageByKeyItem: {
            /**
             * Key Id
             * @description API key id
             */
            key_id: string;
            /**
             * Key Name
             * @description API key name
             */
            key_name: string;
            /**
             * Total Credits
             * @description Total credits consumed by the key
             */
            total_credits: number;
            /**
             * Request Count
             * @description Number of requests
             */
            request_count: number;
            /**
             * Last Used
             * @description ISO 8601 of last use (null if never)
             */
            last_used?: string | null;
        };
        /** UsageLogItem */
        UsageLogItem: {
            /**
             * Id
             * @description Usage log entry id
             */
            id: string;
            /**
             * Endpoint
             * @description Endpoint called
             */
            endpoint: string;
            /**
             * Credits Cost
             * @description Credits consumed
             */
            credits_cost: number;
            /**
             * Status
             * @description Result status
             */
            status: string;
            /**
             * Errors Count
             * @description Errors count
             */
            errors_count: number;
            /**
             * Created At
             * @description ISO 8601 timestamp
             */
            created_at: string;
        };
        /** UsageLogResponse */
        UsageLogResponse: {
            /** Data */
            data: components["schemas"]["UsageLogItem"][];
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /**
             * Service
             * @description Service name
             * @example FalaAI API
             */
            service: string;
            /**
             * Version
             * @description Current API version
             * @example api_v1.21.45
             */
            version: string;
            /**
             * Deploydate
             * @description Deploy timestamp
             * @example 2026-09-22 20260922_023910
             */
            deployDate: string;
        };
        /**
         * WebhookEvent
         * @enum {string}
         */
        WebhookEvent: "subscription.created" | "avulso.completed" | "subscription.upgraded" | "subscription.downgraded" | "subscription.canceled" | "credits.low" | "credits.exhausted" | "subscription.renewed" | "subscription.expired" | "payment.failed";
        /** WebhookItem */
        WebhookItem: {
            /**
             * Id
             * @description Webhook id
             */
            id: string;
            /**
             * User Id
             * @description Owner user id
             */
            user_id: string;
            /**
             * Name
             * @description Webhook name
             */
            name: string;
            /**
             * Url
             * @description Destination URL
             */
            url: string;
            /**
             * Secret
             * @description HMAC signing secret
             */
            secret: string;
            /**
             * Events
             * @description Subscribed events
             */
            events: string[];
            /**
             * Active
             * @description Is active
             */
            active: boolean;
            /**
             * Retry Enabled
             * @description Retry enabled
             */
            retry_enabled: boolean;
            /**
             * Last Delivery At
             * @description ISO 8601 of last delivery
             */
            last_delivery_at?: string | null;
            /**
             * Last Status
             * @description Last HTTP status delivered
             */
            last_status?: number | null;
            /**
             * Failure Count
             * @description Consecutive failures
             * @default 0
             */
            failure_count: number;
            /**
             * Created At
             * @description ISO 8601 created
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO 8601 updated
             */
            updated_at: string;
        };
        /** WebhookListResponse */
        WebhookListResponse: {
            /** Data */
            data: components["schemas"]["WebhookItem"][];
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_transcription_v1_audio_transcriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_transcription_v1_audio_transcriptions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_diagnostic_v1_analyze_diagnostic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_auditoria_risco_v1_analyze_auditoriaRisco_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditoriaRiscoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriaRiscoV2Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_log_v1_usage_log_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                api_key_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_by_key_v1_usage_by_key_get: {
        parameters: {
            query?: {
                key_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageByKeyItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhooks_v1_webhooks_get: {
        parameters: {
            query?: {
                /** @description Pagina (1-indexed) */
                page?: number;
                /** @description Itens por pagina (max 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_webhook_v1_webhooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_webhook_v1_webhooks__webhook_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_webhook_v1_webhooks__webhook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_email_alerts_v1_email_alerts_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailAlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_email_alert_v1_email_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmailAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailAlertItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_email_alert_v1_email_alerts__alert_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmailAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailAlertMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_email_alert_v1_email_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailAlertMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_check_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
